import {useCallback, useEffect, useRef, useState} from 'react';
import {ArrowsClockwise, Books, CheckCircle, FileText, MagnifyingGlass, Plus, Play, Sparkle, X} from '@phosphor-icons/react';
import {api, authorText, type Data, dateText, useErrorText} from './api';
import {Empty, ErrorBox, Pager} from './ui';
import './aiSearch.css';
import {SearchEvaluation} from './SearchEvaluation';
import {candidatePresentation} from './searchPresentation';
import './journalCandidate.css';
import './citationExpand.css';
import './semanticRerank.css';
import './searchCollection.css';

const names: Data = {openalex:'OpenAlex', crossref:'Crossref', pubmed:'PubMed', arxiv:'arXiv'};
const states: Data = {planned:'计划待运行', queued:'等待执行', running:'正在检索', cancelling:'正在停止', verifying:'AI 核验中', completed:'已完成', partial:'部分来源失败', failed:'失败，可重试', cancelled:'已取消', interrupted:'已中断', expanding:'正在扩展分页', linking:'正在扩展引用链'};
const screens: Data = {eligible:'条件通过', pending:'待核验', excluded:'条件不通过'};
const verdicts: Data = {pass:'通过', fail:'不通过', unknown:'未证实'};
const fieldNames: Data = {summaryZh:'中文简述', task:'研究任务', method:'方法', objectives:'优化目标', constraints:'约束'};
const decisions:Data={include:'纳入',exclude:'排除',pending:'待定'};
const metadataLabels:Data={title:'题名',authors:'作者',year:'发表年份',venue:'期刊 / 来源',abstract:'摘要',doi:'DOI',url:'记录链接',oaUrl:'开放获取链接',citationCount:'被引次数',type:'记录类型',pmid:'PMID'};
const size = 30;
const activeStates = ['queued','running','cancelling','verifying','expanding','linking'];
const initialFilters = {screening:'all', source:'all', sort:'screening', q:'', yearFrom:'', yearTo:'', oaOnly:false, type:'all'};

function JournalMetric({match}: {match?:Data}) {
  if (!match?.matched) return <span className="journal-metric unavailable" title="仅以来源 ISSN 与本地期刊索引精确匹配">暂无可核对指标</span>;
  if (!match.jcrYear) return <span className="journal-metric unavailable" title="ISSN 已精确匹配，但本地记录无 JCR 年份">本地期刊 · 无 JCR 年份</span>;
  return <span className="journal-metric" title={`本地期刊索引 · ISSN ${match.issn} · JCR ${match.jcrYear}；期刊指标不代表论文质量`}>
    JCR {match.jcrQuartile||'未分区'} · IF {match.impactFactor??'未知'} · {match.jcrYear}
  </span>;
}

export function AiSearch({tick, notify, fail, onLibrary, onLibraryChange, onRelations, onReader,onJournal}: {tick:number; notify:(m:string)=>void; fail:(e:any)=>void; onLibrary?:(id:string,collectionId?:string)=>void; onLibraryChange?:()=>void; onRelations?:(ids:string[])=>void; onReader?:(id:string,title?:string,page?:number)=>void;onJournal?:(id:number)=>void}) {
  const [sessions,setSessions]=useState<Data[]>([]), [sessionId,setSessionId]=useState<string|null>(null), [session,setSession]=useState<Data|null>(null);
  const [editablePlan,setPlan]=useState<Data|null>(null), [brief,setBrief]=useState(''), [mode,setMode]=useState('quick'), [sources,setSources]=useState(['openalex','crossref']), [useModel,setUseModel]=useState(true);
  const [results,setResults]=useState<Data>({items:[],total:0}), [filters,setFilters]=useState(initialFilters), [page,setPage]=useState(1), [runId,setRunId]=useState('');
  const [selected,setSelected]=useState<string[]>([]), [evidence,setEvidence]=useState<Data|null>(null), [layout,setLayout]=useState('cards'), [busy,setBusy]=useState(''), [error,setError]=useState('');
  const [includeFulltext,setIncludeFulltext]=useState(false);
  const [showEvaluation,setShowEvaluation]=useState(false);
  const [fulltextSources,setFulltextSources]=useState<Data[]>([]), [fulltextJob,setFulltextJob]=useState(''), [fulltextItem,setFulltextItem]=useState('');
  const [journalMatch,setJournalMatch]=useState<Data|null>(null);
  const [collections,setCollections]=useState<Data[]>([]),[collectionId,setCollectionId]=useState(''),[newCollection,setNewCollection]=useState(''),[creatingCollection,setCreatingCollection]=useState(false);
  const [citationLinks,setCitationLinks]=useState<Data[]>([]),[citationJob,setCitationJob]=useState('');
  const [rerankJob,setRerankJob]=useState('');
  const [revision,setRevision]=useState(0), [dirty,setDirty]=useState(false), [showPlan,setShowPlan]=useState(true), [verifyJob,setVerifyJob]=useState(''), [verifyProgress,setVerifyProgress]=useState<Data|null>(null);
  const initialized=useRef(false), request=useRef(0), dirtyRef=useRef(false);
  const evidencePanelRef=useRef<HTMLElement|null>(null);
  dirtyRef.current=dirty;
  const running=activeStates.includes(session?.state), historical=Boolean(runId && runId!==session?.activeRunId);
  const plan=historical ? results.runPlan : editablePlan;
  const queryParams={sessionId,runId:runId||undefined,...filters,limit:size,offset:(page-1)*size};
  const refresh=()=>setRevision(r=>r+1);
  const loadSessions=useCallback(async()=>{const rows=await api('aiSearch.list');setSessions(rows);if(!initialized.current){initialized.current=true;setSessionId(rows[0]?.id||null);}},[]);
  useEffect(()=>{loadSessions().catch(fail);},[tick,revision,loadSessions]);
  useEffect(()=>{api('collections.list').then(setCollections).catch(fail);},[tick]);
  useEffect(()=>{let live=true;if(!sessionId){setSession(null);setPlan(null);return;}api('aiSearch.get',{sessionId}).then(v=>{if(live){setSession(v);if(!dirtyRef.current)setPlan(v.plan);}}).catch(fail);return()=>{live=false;};},[sessionId,tick,revision]);
  useEffect(()=>{if(!sessionId){setResults({items:[],total:0});return;}const id=++request.current;api('aiSearch.results',queryParams).then(v=>{if(id===request.current){setResults(v);if(v.total && (page-1)*size>=v.total)setPage(1);}}).catch(e=>setError(useErrorText(e)));},[sessionId,runId,filters,page,tick,revision]);
  useEffect(()=>{if(!running)return;const timer=setTimeout(refresh,1200);return()=>clearTimeout(timer);},[running,revision,session]);
  useEffect(()=>{if(!verifyJob)return;let live=true;const timer=setInterval(async()=>{try{const jobs=await api('jobs.list');const j=jobs.find((v:Data)=>v.id===verifyJob);if(j&&live){setVerifyProgress(previous=>({sessionId:previous?.sessionId,state:j.state,progress:j.progress||0,message:j.message||''}));if(['completed','failed','cancelled'].includes(j.state)){setVerifyJob('');const failures=j.result?.failed||[];if(j.state==='completed')notify(`AI 核验完成：${j.result?.verified||0} 篇成功，${failures.length} 篇失败`);setError(j.error?.message || (failures.length ? `有 ${failures.length} 篇核验失败；打开论文证据查看原因。${failures.slice(0,2).map((f:Data)=>f.message).join('；')}` : ''));refresh();if(evidence)api('aiSearch.evidence',{candidateId:evidence.id}).then(setEvidence).catch(fail);}}}catch(e){if(live)setError(useErrorText(e));}},1000);return()=>{live=false;clearInterval(timer);};},[verifyJob,evidence?.id]);
  useEffect(()=>{if(!evidence?.importedItemId){setFulltextSources([]);return;}let live=true;api('fulltext.sources',{itemId:evidence.importedItemId}).then((rows:Data[])=>{if(live)setFulltextSources(rows);}).catch(fail);return()=>{live=false;};},[evidence?.importedItemId,revision]);
  useEffect(()=>{setJournalMatch(null);if(!evidence?.id||historical)return;let live=true;api('aiSearch.journalMatch',{candidateId:evidence.id}).then(value=>live&&setJournalMatch(value)).catch(()=>live&&setJournalMatch({matched:false,reason:'本地期刊索引暂不可用'}));return()=>{live=false;};},[evidence?.id,historical]);
  useEffect(()=>{if(!evidence?.id||historical){setCitationLinks([]);return;}api('aiSearch.citationLinks',{sessionId,candidateId:evidence.id}).then(setCitationLinks).catch(()=>setCitationLinks([]));},[evidence?.id,historical,sessionId,tick,revision]);
  useEffect(()=>{if(evidence?.id)evidencePanelRef.current?.scrollTo({top:0});},[evidence?.id]);
  useEffect(()=>{if(!citationJob)return;const timer=setInterval(async()=>{try{const job=(await api('jobs.list')).find((value:Data)=>value.id===citationJob);if(job&&['completed','failed','cancelled'].includes(job.state)){setCitationJob('');if(job.state==='completed')notify(`引用链返回 ${job.result?.received||0} 条，新增 ${job.result?.accepted||0} 篇`);else setError(job.error?.message||'引用链扩展失败');refresh();}}catch(e){setError(useErrorText(e));}},1000);return()=>clearInterval(timer);},[citationJob]);
  useEffect(()=>{if(!rerankJob)return;const timer=setInterval(async()=>{try{const job=(await api('jobs.list')).find((value:Data)=>value.id===rerankJob);if(job&&['completed','failed','cancelled'].includes(job.state)){setRerankJob('');if(job.state==='completed')notify(`已有 ${job.result?.scored||0} 篇取得可核对的语义排序建议`);else setError(job.error?.message||'语义重排失败');refresh();if(evidence?.id)api('aiSearch.evidence',{candidateId:evidence.id}).then(setEvidence).catch(fail);}}catch(e){setError(useErrorText(e));}},1000);return()=>clearInterval(timer);},[rerankJob,evidence?.id]);
  useEffect(()=>{if(!fulltextJob)return;let live=true;const timer=setInterval(async()=>{try{const jobs=await api('jobs.list');const job=jobs.find((v:Data)=>v.id===fulltextJob);if(job&&['completed','failed','cancelled'].includes(job.state)&&live){setFulltextJob('');setFulltextSources(await api('fulltext.sources',{itemId:fulltextItem}));if(job.state==='completed'&&job.result?.attachmentId){notify('PDF 已加入文献库，正在建立全文索引');onReader?.(job.result.attachmentId,evidence?.title);}else setError(job.error?.message||'全文获取未完成，请检查来源或手动导入');refresh();}}catch(e){if(live)setError(useErrorText(e));}},1000);return()=>{live=false;clearInterval(timer);};},[fulltextJob,fulltextItem,evidence?.title]);
  useEffect(()=>{if(session?.id)setShowPlan(!session.activeRunId);},[session?.id]);
  function choose(id:string|null){setSessionId(id);setSession(null);setPlan(null);setDirty(false);dirtyRef.current=false;setRunId('');setSelected([]);setEvidence(null);setFulltextSources([]);setPage(1);setError('');setShowEvaluation(false);}
  function update(patch:Data){setPlan(p=>p?{...p,...patch}:p);setDirty(true);dirtyRef.current=true;}
  function filter(patch:Partial<typeof initialFilters>){setFilters(f=>({...f,...patch}));setPage(1);setSelected([]);}
  async function action(name:string, fn:()=>Promise<any>){setBusy(name);setError('');try{return await fn();}catch(e){setError(useErrorText(e));}finally{setBusy('');}}
  async function createCollection(){const name=newCollection.trim();if(!name)return;await action('collection',async()=>{const created=await api('collections.edit',{action:'create',name});setCollections(await api('collections.list'));setCollectionId(created.id);setNewCollection('');setCreatingCollection(false);onLibraryChange?.();notify(`已创建并选中集合「${name}」`);});}
  async function create(){await action('create',async()=>{const v=await api('aiSearch.create',{brief,mode,sources,useModel});choose(v.id);setSession(v);setPlan(v.plan);setBrief('');refresh();});}
  async function save(run=false){if(!session||!plan||historical)return;await action('save',async()=>{const v=await api('aiSearch.savePlan',{sessionId,plan});setDirty(false);dirtyRef.current=false;setSession(v);setPlan(v.plan);if(run){await api('aiSearch.run',{sessionId});setSession({...v,state:'queued'});setShowPlan(false);setRunId('');setEvidence(null);setSelected([]);setPage(1);}refresh();});}
  function toggle(id:string){setSelected(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);}
  async function show(item:Data){if(historical){setEvidence(item);return;}await action('detail',async()=>setEvidence(await api('aiSearch.evidence',{candidateId:item.id})));}
  async function importPapers(ids=selected, destination=''){await action('import',async()=>{const v=await api('aiSearch.import',{candidateIds:ids,collectionId:collectionId||undefined});const all=[...v.imported,...v.existing].map((r:Data)=>r.itemId);notify(`已保存到${collectionId?('「'+(collections.find(c=>c.id===collectionId)?.name||'所选集合')+'」'):'我的文献'}：新导入 ${v.imported.length} 篇，库内已有 ${v.existing.length} 篇`);onLibraryChange?.();refresh();if(evidence?.id===ids[0])setEvidence(await api('aiSearch.evidence',{candidateId:ids[0]}));if(destination==='library'&&all.length)onLibrary?.(all[0],collectionId||undefined);if(destination==='relations'&&all.length)onRelations?.(all);if(destination==='fulltext'&&all.length){const rows=await api('fulltext.sources',{itemId:all[0]});setFulltextSources(rows);const source=rows.find((row:Data)=>row.origin==='oa');if(source){const job=await api('fulltext.obtain',{itemId:all[0],sourceId:source.id});setFulltextItem(all[0]);setFulltextJob(job.jobId);notify('已保存文献，正在检查并获取开放全文');}else{onLibrary?.(all[0],collectionId||undefined);notify('已保存题录，未找到开放全文候选；可在附件页手动添加来源');}}});}
  async function verify(){await action('verify',async()=>{const job=await api('aiSearch.verify',{candidateIds:selected,allowRemote:true,includeFulltext});setVerifyJob(job.jobId);setVerifyProgress({sessionId,state:'pending',progress:0,message:'等待开始'});refresh();notify(`已提交 ${selected.length} 篇摘要核验；逐字证据会在返回后校验`);});}
  async function exportMatrix(){await action('export',async()=>{const all:Data[]=[];let offset=0;while(true){const r=await api('aiSearch.results',{...queryParams,offset,limit:200});all.push(...r.items);if(!r.hasMore)break;offset+=r.items.length;}const rows=[['题名','作者','年份','期刊','JCR 分区','影响因子','JCR 年份','DOI','条件判断','人工决定','核验方式','中文简述','研究任务','方法','目标','约束','条件证据'],...all.map(r=>[r.title,authorText(r),r.year,r.venue,r.journalMatch?.jcrQuartile||'',r.journalMatch?.impactFactor??'',r.journalMatch?.jcrYear||'',r.doi,screens[r.screening],r.decision?.decision||'',r.verification,...Object.keys(fieldNames).map(k=>r.fields?.[k]?.text||''),JSON.stringify(r.checks)])];const csv='\ufeff'+rows.map(row=>row.map(cell=>{let s=String(cell??'');if(/^[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='研究矩阵.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify(`已导出当前筛选的全部 ${all.length} 条`);});}
  function renderRefs(refs:Data[]=[]){return refs.map((r,i)=>{const e=evidence?.evidence?.find((v:Data)=>v.id===r.evidenceId);return <blockquote key={i}>{r.quote}<small>{names[e?.source]||e?.source} · {e?.kind==='fulltext'?`PDF 第${e.page}页`:e?.kind==='abstract'?'摘要':'题名'}</small>{e?.attachmentId&&<button onClick={()=>onReader?.(e.attachmentId,evidence?.title,e.page)}>跳转原文页</button>}</blockquote>;});}
  function renderOverview(){if(!evidence)return null;const provenance=evidence.fieldSources?.abstract;const chosen=provenance?.values?.find((value:Data)=>value.source===provenance.chosenSource);const summary=evidence.verification?.startsWith('model')?evidence.fields?.summaryZh:null;return <div className="paper-source-overview"><section><h4>摘要 <small>{provenance?.chosenSource?`来源：${names[provenance.chosenSource]||provenance.chosenSource}`:'来源未标明'}</small></h4>{chosen?.retrievedAt&&<small>记录获取于 {dateText(chosen.retrievedAt)}</small>}<p className="paper-source-abstract">{evidence.abstract||'来源未提供摘要；目前只能依据题名核验。'}</p></section>{summary?.text&&<section><h4>AI 中文简述</h4><small>{evidence.coverageNote||'请结合下方原句核对；AI 简述不是论文全文。'}</small><p>{summary.text}</p>{renderRefs(summary.references)}</section>}</div>;}
  return <div className="ai-search-page search-v2">
    <aside className="ai-session-rail"><div className="ai-rail-heading"><strong>研究检索</strong><button aria-label="刷新检索历史" onClick={refresh}><ArrowsClockwise/></button></div><button className="new-search" onClick={()=>choose(null)}><Plus/>新建研究任务</button><div className="ai-history">{sessions.map(s=><button key={s.id} className={sessionId===s.id?'active':''} onClick={()=>choose(s.id)}><div><strong>{s.title}</strong><small>{states[s.state]} · {s.resultCount} 篇</small></div></button>)}</div><p className="ai-rail-note">计划与结果版本保存在本机。</p></aside>
    <main className="ai-search-workspace">{!session?<section className="ai-composer"><div className="ai-composer-hero"><span className="eyebrow">LITERATURE DISCOVERY</span><h1>从研究问题<br/>到可检查的证据</h1><p>确认术语、检索式和必须条件，再检索与筛选。</p></div><div className="ai-composer-card"><label>研究任务<textarea aria-label="研究任务" rows={6} value={brief} onChange={e=>setBrief(e.target.value)} placeholder="例如：多车间、多目标柔性作业调度，关注代理模型与计算效率。"/></label><div className="segmented"><button className={mode==='quick'?'active':''} onClick={()=>setMode('quick')}>快速发现</button><button className={mode==='deep'?'active':''} onClick={()=>setMode('deep')}>扩展检索与核验</button></div><div className="source-toggles">{Object.entries(names).map(([k,v])=><label key={k}><input type="checkbox" checked={sources.includes(k)} onChange={()=>setSources(s=>s.includes(k)?s.filter(x=>x!==k):[...s,k])}/>{v}</label>)}</div><p>工程主题默认 OpenAlex / Crossref；可按学科补充 PubMed 或 arXiv。</p><label className="model-plan"><input type="checkbox" checked={useModel} onChange={e=>setUseModel(e.target.checked)}/>将本次研究任务发送到已配置 AI 服务优化计划；未配置时使用本地术语建议。</label><button className="primary" disabled={Boolean(busy)||brief.trim().length<12||!sources.length} onClick={create}><Sparkle/>{busy?'正在生成…':'生成检索计划'}</button></div></section>:<>
      <header className="ai-workspace-header"><div><span className="eyebrow">RESEARCH TASK</span><h1>{session.title}</h1><p>{states[session.state]} · {dirty?'计划有未保存修改':'计划已保存'}</p></div><div className="ai-header-actions"><button onClick={()=>setShowPlan(v=>!v)}>{showPlan?'收起计划':'展开计划'}</button><button onClick={refresh}><ArrowsClockwise/>刷新</button>{!running&&!historical&&results.sourceCursors?.some((c:Data)=>c.hasMore)&&<button disabled={Boolean(busy)} onClick={()=>action('expand',async()=>{await api('aiSearch.expand',{sessionId,pageBudget:3});notify('正在按来源频控继续获取下一页');refresh();})}>继续扩展分页</button>}{running?<button disabled={session.state==='cancelling'} onClick={()=>action('cancel',async()=>{await api('aiSearch.cancel',{sessionId});refresh();})}>取消检索</button>:<button className="primary" disabled={Boolean(busy)||historical} onClick={()=>save(true)}><Play/>运行检索</button>}</div></header>
      {session.planningWarning&&<div className="ai-warning">AI规划不可用：{session.planningWarning}</div>}
      <div className={'ai-workspace-grid '+(!showPlan?'plan-hidden':'')}>
        {showPlan&&<section className="ai-plan-panel"><div className="panel-heading"><h2>检索计划</h2><button disabled={running||Boolean(busy)||historical} onClick={()=>save()}>保存计划</button></div><fieldset disabled={running||Boolean(busy)||historical}><label>计划说明<textarea value={plan?.summary||''} onChange={e=>update({summary:e.target.value})}/></label><div className="plan-section"><span>术语映射（可编辑）</span>{(plan?.termMappings||[]).map((m:Data,i:number)=><label key={i}>{m.term}<input value={m.translation} onChange={e=>update({termMappings:plan!.termMappings.map((v:Data,j:number)=>i===j?{...v,translation:e.target.value}:v)})}/></label>)}<small>术语映射用于核对；实际查询以以下检索式为准。</small></div><div className="plan-section"><span>全部启用的检索式都会执行</span>{plan?.queries.map((q:Data,i:number)=><div className="query-editor" key={q.id}><label><input type="checkbox" checked={q.enabled!==false} onChange={e=>update({queries:plan!.queries.map((v:Data,j:number)=>i===j?{...v,enabled:e.target.checked}:v)})}/>检索式 {i+1}</label><textarea aria-label={'检索式 '+(i+1)} value={q.query} onChange={e=>update({queries:plan!.queries.map((v:Data,j:number)=>i===j?{...v,query:e.target.value}:v)})}/><button aria-label="移除此检索式" onClick={()=>update({queries:plan!.queries.filter((_:Data,j:number)=>j!==i)})}><X/></button></div>)}{(plan?.queries.length||0)<6&&<button onClick={()=>update({queries:[...plan!.queries,{id:crypto.randomUUID(),query:'',label:'补充查询',enabled:true}]})}><Plus/>添加检索式</button>}</div>
        <div className="plan-section"><span>逐篇核验条件</span><small>规则只识别明示主题和反例；复杂条件需 AI 或人工核验。</small>{(plan?.criteria||[]).map((c:Data,i:number)=><div className="criterion-editor" key={c.id}><input aria-label={'条件说明 '+(i+1)} value={c.label} onChange={e=>update({criteria:plan!.criteria.map((v:Data,j:number)=>i===j?{...v,label:e.target.value}:v)})}/><div><label><input type="checkbox" checked={c.required} onChange={e=>update({criteria:plan!.criteria.map((v:Data,j:number)=>i===j?{...v,required:e.target.checked}:v)})}/>必须满足</label><select aria-label={'条件类型 '+(i+1)} value={c.kind} onChange={e=>update({criteria:plan!.criteria.map((v:Data,j:number)=>i===j?{...v,kind:e.target.value}:v)})}><option value="include">纳入主题</option><option value="exclude">排除主题</option></select><button aria-label="移除此条件" onClick={()=>update({criteria:plan!.criteria.filter((_:Data,j:number)=>i!==j)})}><X/></button></div><label>同义词（分号分隔）<textarea value={c.terms.join('; ')} onChange={e=>update({criteria:plan!.criteria.map((v:Data,j:number)=>i===j?{...v,terms:e.target.value.split(/[;；]/)}:v)})}/></label><label>明确反例（分号分隔）<input value={c.negativeTerms.join('; ')} onChange={e=>update({criteria:plan!.criteria.map((v:Data,j:number)=>i===j?{...v,negativeTerms:e.target.value.split(/[;；]/)}:v)})}/></label></div>)}<button disabled={(plan?.criteria?.length||0)>=16} onClick={()=>update({criteria:[...(plan?.criteria||[]),{id:crypto.randomUUID(),label:'新条件',kind:'include',required:true,terms:[],negativeTerms:[]}]})}><Plus/>添加条件</button></div><div className="plan-sources">{Object.entries(names).map(([k,v])=><label key={k}><input type="checkbox" checked={plan?.sources.includes(k)||false} onChange={()=>update({sources:plan!.sources.includes(k)?plan!.sources.filter((x:string)=>x!==k):[...plan!.sources,k]})}/>{v}</label>)}</div></fieldset></section>}
        <section className="ai-results-panel"><div className="results-heading"><div><h2>候选文献与研究矩阵</h2><p>词汇分仅用于召回排序；条件判断与 AI 核验单独展示。</p>{results.journalIndexMessage&&<p className="journal-index-note">期刊指标暂不可用：{results.journalIndexMessage}</p>}<button disabled={!session.activeRunId||running||historical||Boolean(rerankJob)} onClick={()=>action('rerank',async()=>{const job=await api('aiSearch.rerank',{sessionId});setRerankJob(job.jobId);notify('仅将前 20 篇公开题名与摘要发送给已配置的 AI 服务');})}>AI 语义重排</button><button disabled={!session.activeRunId||running} onClick={()=>setShowEvaluation(v=>!v)}>{showEvaluation?'收起评测':'质量评测'}</button></div></div><div className="version-toolbar"><select aria-label="检索结果版本" value={runId} onChange={e=>{setRunId(e.target.value);setSelected([]);setEvidence(null);setPage(1);}}><option value="">最新结果</option>{session.runs?.map((r:Data,i:number)=><option key={r.id} value={r.id}>第 {session.runs.length-i} 次 · {states[r.state]} · {dateText(r.createdAt)}</option>)}</select><button onClick={()=>setLayout(v=>v==='cards'?'matrix':'cards')}>{layout==='cards'?'研究矩阵':'卡片视图'}</button><button disabled={!results.total||Boolean(busy)||running} onClick={exportMatrix}>导出全部筛选结果</button></div>
        <details className="query-log"><summary>查询执行记录 · {results.queryRuns?.length||0} 条</summary>{results.sourceCursors?.length>0&&<p>分页进度：{results.sourceCursors.filter((c:Data)=>c.hasMore).length} 条检索式仍可扩展；每式最多 300 条。点击顶部“继续扩展分页”每次最多取 3 页。</p>}{results.queryRuns?.map((q:Data,i:number)=><p key={i}><b>{names[q.source]}</b> · {states[q.state]||q.state} · {q.received} 条 · {q.elapsedMs} ms<br/>{q.query}{Boolean(q.truncated)&&<small>达到本次请求上限，非完整召回</small>}{q.error&&<small className="error">{q.error}</small>}</p>)}</details>
        {showEvaluation&&session.activeRunId&&<SearchEvaluation sessionId={sessionId!} runId={runId||session.activeRunId}/>}
        <div className="search-save-target"><label>保存到<select aria-label="检索结果保存集合" value={collectionId} onChange={e=>setCollectionId(e.target.value)} disabled={Boolean(busy)||historical}><option value="">我的文献（不指定集合）</option>{collections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button disabled={Boolean(busy)||historical} onClick={()=>setCreatingCollection(v=>!v)}><Plus/>新建集合</button>{creatingCollection&&<form onSubmit={e=>{e.preventDefault();createCollection();}}><input aria-label="新集合名称" placeholder="输入集合名称" maxLength={200} value={newCollection} onChange={e=>setNewCollection(e.target.value)}/><button type="submit" disabled={!newCollection.trim()||Boolean(busy)}>创建并选中</button></form>}</div>
        <div className="result-filters"><input aria-label="结果内检索" placeholder="在题名、摘要、DOI中查找" value={filters.q} onChange={e=>filter({q:e.target.value})}/><select aria-label="条件筛选" value={filters.screening} onChange={e=>filter({screening:e.target.value})}><option value="all">全部条件状态</option>{Object.entries(screens).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="数据来源筛选" value={filters.source} onChange={e=>filter({source:e.target.value})}><option value="all">全部来源</option>{Object.entries(names).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="结果排序" value={filters.sort} onChange={e=>filter({sort:e.target.value})}><option value="screening">条件匹配优先</option><option value="score">词汇分优先</option><option value="semantic">AI 建议优先（已核对原句 {results.semanticCount||0} 篇）</option><option value="year">年份优先</option><option value="citations">引用量优先</option><option value="title">标题 A–Z</option></select><input type="number" aria-label="起始年份" placeholder="起始年份" value={filters.yearFrom} onChange={e=>filter({yearFrom:e.target.value})}/><input type="number" aria-label="截止年份" placeholder="截止年份" value={filters.yearTo} onChange={e=>filter({yearTo:e.target.value})}/><select aria-label="文章类型" value={filters.type} onChange={e=>filter({type:e.target.value})}><option value="all">全部记录类型</option><option value="journal-article">期刊论文（Crossref）</option><option value="article">文章</option><option value="review">综述标记</option><option value="article-journal">期刊论文</option></select><label><input type="checkbox" checked={filters.oaOnly} onChange={e=>filter({oaOnly:e.target.checked})}/>有开放链接</label></div>
        <p className="screen-counts">通过 {results.counts?.eligible||0} · 待核验 {results.counts?.pending||0} · 不通过 {results.counts?.excluded||0}{historical?' · 历史快照，只读':''}</p>
        {layout==='cards'?<div className="ai-result-cards">{results.items.map((r:Data)=>{const view=candidatePresentation(r);return <article key={r.id} className={'ai-result-card '+(selected.includes(r.id)?'selected':'')}><button className="result-select" aria-label={'选择 '+r.title} disabled={historical||running} onClick={()=>toggle(r.id)}><i>{selected.includes(r.id)&&<CheckCircle/>}</i></button><div className="result-card-main"><div className="result-title-row"><span className={'screen-badge '+r.screening}>{screens[r.screening]}</span><button className="paper-title" onClick={()=>show(r)}>{r.title}</button></div><p className="result-meta">{authorText(r)||'作者待补充'} · {r.year||'年份未知'} · {r.venue}</p>{r.issn&&<JournalMetric match={r.journalMatch}/>}<div className="candidate-judgement"><strong>{view.judgement}</strong><small>核验材料：{view.material}</small></div>{r.verification?.startsWith('model')&&r.fields?.summaryZh?.text&&<p className="result-explanation">{view.summary}</p>}{view.quote&&<p className="candidate-quote">原句：{view.quote}</p>}<div className="result-tags">{r.sources.map((s:string)=><span key={s}>{names[s]}</span>)}<span>{r.verification?.startsWith('model')?'AI核验 · 原句已校验':'规则核验'}</span><span>必需条件 {view.passed} 通过 / {view.unknown} 待核验 / {view.failed} 不通过</span>{r.verificationError&&<span className="verification-failed">AI 核验失败 · 查看证据</span>}{r.semantic&&<span>AI 建议 {Math.round(r.semantic.score*100)} · 原句已核对</span>}{r.doi&&<span>{r.doi}</span>}{r.oaUrl&&<span>开放链接</span>}{r.decision&&<span>人工：{decisions[r.decision.decision]}</span>}</div></div><div className="result-card-actions"><strong>{Math.round(r.score*100)}<small>词汇分</small></strong><button className="detail-action" onClick={()=>show(r)}>查看证据</button><button className="save-action" disabled={historical||running||Boolean(busy)} onClick={()=>importPapers([r.id])}>{collectionId?'存入集合':'保存题录'}</button></div></article>})}</div>:<div className="research-matrix"><table><thead><tr><th>选择</th><th>论文</th><th>年份</th><th>期刊 / 来源</th><th>本地期刊指标</th><th>被引</th><th>开放链接</th><th>条件判断</th><th>核验材料</th>{Object.values(fieldNames).map((v:any)=><th key={v}>{v}</th>)}</tr></thead><tbody>{results.items.map((r:Data)=><tr key={r.id}><td><input type="checkbox" aria-label={'选择 '+r.title} disabled={historical||running} checked={selected.includes(r.id)} onChange={()=>toggle(r.id)}/></td><td><button onClick={()=>show(r)}>{r.title}</button><small>{authorText(r)||'作者待补充'}</small></td><td>{r.year||'—'}</td><td>{r.venue||'—'}</td><td><JournalMetric match={r.journalMatch}/></td><td>{r.citationCount??'—'}</td><td>{r.oaUrl?'有候选链接':'未找到'}</td><td><span className={'screen-badge '+r.screening}>{screens[r.screening]}</span><small>{candidatePresentation(r).judgement}</small></td><td>{candidatePresentation(r).material}</td>{Object.keys(fieldNames).map(k=><td key={k}>{r.fields?.[k]?.text||'尚无证据提取'}</td>)}</tr>)}</tbody></table></div>}
        {!results.items.length&&<Empty icon={<MagnifyingGlass/>} title={running?'正在获取候选':'当前没有结果'}>可调整筛选，或检查计划后运行检索。</Empty>}
        <Pager page={page} total={results.total} size={size} setPage={p=>{setPage(p);setSelected([]);}}/>
        <div className="result-footer"><span>已选 {selected.length} 篇</span><button className="primary" disabled={!selected.length||Boolean(busy)||running||historical} onClick={()=>importPapers()}><Books/>{collectionId?'导入所选到集合':'导入所选'}</button><button disabled={selected.length<2||Boolean(busy)||running||historical} onClick={()=>importPapers(selected,'relations')}>导入并关联</button></div>
        <div className="verification-action"><p>批量中文解读与条件核验：每篇各发送 1 次模型请求，最多 20 篇；实际费用取决于你配置的服务商。缺少摘要时仅能依据题名，不能推断全文。</p>{selected.length>0&&<p>已选择 {selected.length} 篇，预计 {selected.length} 次模型请求。</p>}<label><input type="checkbox" checked={includeFulltext} onChange={e=>setIncludeFulltext(e.target.checked)}/>同时发送已导入文献的PDF片段（每篇最多前40页中30000字符）</label><button disabled={!selected.length||selected.length>20||Boolean(busy)||Boolean(verifyJob)||running||historical} onClick={verify}><Sparkle/>{includeFulltext?'发送所选摘要及PDF片段并核验':'批量生成中文解读并核验'}</button>{verifyProgress?.sessionId===sessionId&&<div className="verify-progress" role="status"><span>{verifyProgress.state==='completed'?'本批次已完成':verifyProgress.message||'等待开始'}</span><progress value={verifyProgress.progress||0} max={1}/></div>}</div>
        </section>
        <aside ref={evidencePanelRef} className={"ai-evidence-panel "+(evidence?"has-evidence":"")}><div className="panel-heading"><h2>论文与证据</h2>{evidence&&<button aria-label="关闭证据" onClick={()=>setEvidence(null)}><X/></button>}</div>{evidence?<><h3>{evidence.title}</h3><p>{authorText(evidence)} · {evidence.year}</p><span className={'screen-badge '+evidence.screening}>{screens[evidence.screening]}</span><p>{evidence.coverageNote || `材料：${evidence.abstract?'题名与摘要':'仅题名'}；未核验全文。`}</p>{evidence.verificationError&&<ErrorBox message={evidence.verificationError}/>}{evidence.doi&&<p>DOI：{evidence.doi}</p>}{renderOverview()}
        {journalMatch?.matched?<div className="journal-candidate-match"><strong>本地期刊精确匹配</strong><p>{journalMatch.name} · ISSN {journalMatch.issn}{journalMatch.jcrYear&&` · ${journalMatch.jcrYear} JCR ${journalMatch.jcrQuartile||'未知'}`}{journalMatch.impactFactor!=null&&` · IF ${journalMatch.impactFactor}`}</p><button onClick={()=>onJournal?.(journalMatch.journalId)}>查看期刊资料</button></div>:journalMatch?.reason&&<p className="muted">期刊数据：{journalMatch.reason}</p>}{evidence.semantic&&<div className="semantic-evidence"><strong>AI 排序建议 {Math.round(evidence.semantic.score*100)}</strong><p>{evidence.semantic.reason}</p><blockquote>{evidence.semantic.quote}</blockquote><small>原句已在题名或摘要中核对；不代表全文核验。</small></div>}<div className="citation-expand"><strong>引用链（OpenAlex）</strong><p>仅获取当前论文直接引用或被引用的前 20 条；来源关系是书目链接，需阅读原文核对。</p><div><button disabled={historical||running||Boolean(citationJob)||!evidence.variants?.some((v:Data)=>v.source==='openalex')} onClick={()=>action('citations',async()=>{const job=await api('aiSearch.citationExpand',{sessionId,candidateId:evidence.id,direction:'references'});setCitationJob(job.jobId);})}>查找参考文献</button><button disabled={historical||running||Boolean(citationJob)||!evidence.variants?.some((v:Data)=>v.source==='openalex')} onClick={()=>action('citations',async()=>{const job=await api('aiSearch.citationExpand',{sessionId,candidateId:evidence.id,direction:'citing'});setCitationJob(job.jobId);})}>查找引用此文</button></div>{citationLinks.map(link=><article className="citation-record" key={link.relatedId+link.direction}><strong>{link.direction==='references'?'参考文献':'引用本文'}</strong><p>{link.title}</p><small>{link.year||'年份未知'} · {link.venue||'发表位置待核对'}{link.doi&&` · DOI ${link.doi}`} · 关系来源：{names[link.source]||link.source}</small>{link.available&&<button onClick={()=>show({id:link.relatedId})}>查看该文证据</button>}</article>)}</div><div className="evidence-actions">{evidence.url&&<button onClick={()=>window.research.external(evidence.url).catch(fail)}>原始记录</button>}{evidence.oaUrl&&<button onClick={()=>window.research.external(evidence.oaUrl).catch(fail)}>开放链接</button>}<button disabled={historical||running||Boolean(busy)} onClick={()=>importPapers([evidence.id],'library')}>{collectionId?'保存到所选集合':'保存题录'}</button>{evidence.oaUrl&&<button disabled={historical||running||Boolean(busy)||Boolean(fulltextJob)} onClick={()=>importPapers([evidence.id],'fulltext')}>{fulltextJob?'正在获取…':'保存并获取全文'}</button>}</div>
        {fulltextSources.length>0&&<div className="fulltext-sources"><strong>全文来源状态</strong>{fulltextSources.map(source=><p key={source.id}>{source.origin==='oa'?'开放链接':'原始记录'} · {({candidate:'待检查',checking:'检查中',ready:'PDF可获取',downloading:'下载中',attached:'已挂接',indexed:'已索引',landing:'论文落地页',failed:'获取失败'} as Data)[source.state]||source.state}{source.error&&` · ${source.error}`}</p>)}</div>}
        {!historical&&<label>人工筛选决定<select aria-label="人工筛选决定" value={evidence.decision?.decision||'pending'} disabled={running} onChange={e=>action('decision',async()=>{setEvidence(await api('aiSearch.decision',{candidateId:evidence.id,decision:e.target.value}));refresh();})}><option value="pending">待定</option><option value="include">纳入</option><option value="exclude">排除</option></select></label>}
        <div className="criterion-checks">{evidence.checks?.map((c:Data)=><details key={c.id} open={c.status!=='pass'}><summary><span className={'verdict '+c.status}>{verdicts[c.status]}</span>{c.label} · {c.required?'必须':'偏好'}</summary><p>{c.reason}</p>{renderRefs(c.references)}</details>)}</div>
        {Object.entries(evidence.fields||{}).filter(([k])=>k!=='summaryZh').map(([k,v]:any)=><details key={k}><summary>{fieldNames[k]}：{v.text}</summary>{renderRefs(v.references)}</details>)}<div className="evidence-list">{evidence.evidence?.map((e:Data)=><article key={e.id||e.label}><span>{e.label} · {names[e.source]||e.source}</span><p>{e.text}</p></article>)}</div><details><summary>字段来源与冲突</summary>{Object.entries(evidence.fieldSources||{}).map(([k,v]:any)=><div key={k}><b>{metadataLabels[k]||k} · {names[v.chosenSource]||'未知'}</b>{v.values.map((x:Data,i:number)=><p key={i}>{names[x.source]}：{typeof x.value==='object'?JSON.stringify(x.value):String(x.value)}<small>{dateText(x.retrievedAt)}</small></p>)}</div>)}</details></>:<div className="evidence-empty"><FileText/><p>点击论文题名或“查看证据”。勾选只用于批量操作。</p></div>}</aside>
      </div></>}{error&&<ErrorBox message={error}/>}</main>
  </div>;
}
