import {useCallback, useEffect, useRef, useState, type ReactNode} from 'react';
import {BookOpen, Books, FilePdf, Notebook, Compass, Folder, Plus, Clock, Circle, Star, Copy, Trash, Database, GearSix, MagnifyingGlass, Minus, Square, X, ArrowSquareOut, DotsThree, Tag, CheckCircle, ArrowsClockwise, Sparkle, List} from '@phosphor-icons/react';
import {api, files, type Data, authorText, yearText, stateText, useErrorText} from './api';
import {Modal, Empty, Busy, ErrorBox, Search, Pager} from './ui';
import {ItemEditor, ImportPreview, MetadataDialog, CitationDialog, CollectionDialog} from './dialogs';
import {Inspector} from './Inspector';
import {Notes} from './Notes';
import {Reader} from './Reader';
import {Journals} from './Journals';
import {DataCenter, Settings} from './Settings';
import {AiSearch} from './AiSearch';
import {Relations} from './Relations';
import {Writing} from './Writing';
import {Comparison} from './Comparison';
import {ResearchAsk} from './ResearchAsk';
import {ResearchWorkspace} from './ResearchWorkspace';
import {AdvancedSearch} from './AdvancedSearch';
import './readerCompare.css';
import brandLogo from './assets/logo-whale.png';
import {useVirtualizer} from '@tanstack/react-virtual';

export default function App() {
  const [view, setView] = useState('all'), [module, setModule] = useState('library'), [collection, setCollection] = useState<string | null>(null);
  const [stats, setStats] = useState<Data>({items: 0, tags: [], years: []}), [collections, setCollections] = useState<Data[]>([]);
  const [tick, setTick] = useState(0), [q, setQ] = useState(''), [query, setQuery] = useState(''), [filters, setFilters] = useState<Data>({});
  const [result, setResult] = useState<Data>({items: [], total: 0}), [page, setPage] = useState(1), [sort, setSort] = useState('created');
  const [selected, setSelected] = useState<string[]>([]), [item, setItem] = useState<Data | null>(null), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  const [modal, setModal] = useState<Data | null>(null), [toast, setToast] = useState(''), [tabs, setTabs] = useState<Data[]>([]), [activeTab, setActiveTab] = useState('library');
  const [duplicates, setDuplicates] = useState<Data[]>([]), [undo, setUndo] = useState<string | null>(null), [status, setStatus] = useState('所有更改保存在本机');
  const [collapsed, setCollapsed] = useState(localStorage.getItem('inspectorCollapsed') === 'true');
  const [columns, setColumns] = useState<Data>(() => {try {return JSON.parse(localStorage.getItem('tableColumns') || '{"authors":true,"year":true,"container":true,"state":true}');} catch {return {authors:true,year:true,container:true,state:true};}});
  const [widths, setWidths] = useState<Data>(() => {try {return JSON.parse(localStorage.getItem('tableWidths') || '{"authors":100,"year":52,"container":105,"state":72}');} catch {return {authors:100,year:52,container:105,state:72};}});
  const [context, setContext] = useState<Data | null>(null), [batchTags, setBatchTags] = useState('');
  const [relationSeed, setRelationSeed] = useState<string[]>([]);
  const [askSeed, setAskSeed] = useState<{itemId:string;question:string}|null>(null);
  const [compareId, setCompareId] = useState('');
  const [readingSidebarCollapsed, setReadingSidebarCollapsed] = useState(() => localStorage.getItem('readingSidebarCollapsed') !== 'false');
  useEffect(() => {localStorage.setItem('inspectorCollapsed', String(collapsed)); localStorage.setItem('tableColumns', JSON.stringify(columns)); localStorage.setItem('tableWidths', JSON.stringify(widths));}, [collapsed, columns, widths]);
  useEffect(() => {localStorage.setItem('readingSidebarCollapsed', String(readingSidebarCollapsed));}, [readingSidebarCollapsed]);
  function resizeColumn(event: any, key: string) {const x = event.clientX, width = widths[key]; const move = (e: PointerEvent) => setWidths(old => ({...old, [key]: Math.max(44, Math.min(300, width + e.clientX - x))})); const end = () => {window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', end);}; window.addEventListener('pointermove', move); window.addEventListener('pointerup', end); event.preventDefault();}
  const gridColumns = ['27px', 'minmax(160px,1fr)', ...['authors','year','container','state'].filter(k => columns[k]).map(k => widths[k] + 'px')].join(' ');
  const scroll = useRef<HTMLDivElement>(null), requestId = useRef(0);
  const refresh = useCallback(() => setTick(x => x + 1), []);
  const notify = useCallback((message: string) => setToast(message), []);
  const fail = useCallback((e: any) => notify(useErrorText(e)), [notify]);
  const close = useCallback(() => setModal(null), []);
  const run = useCallback(async (fn: () => Promise<any>, message?: string) => {try {const value = await fn(); if (message) notify(message); refresh(); return value;} catch (e) {fail(e); return null;}}, [fail, notify, refresh]);
  const importFiles = useCallback(async (itemId?: string) => {try {const preview = await files(itemId ? 'attach' : 'import', {itemId}); if (preview) setModal({type: 'import', preview});} catch(e) {fail(e);}}, [fail]);
  useEffect(() => {const timer = setTimeout(() => {setQuery(q); setPage(1);}, 200); return () => clearTimeout(timer);}, [q]);
  useEffect(() => {if (!toast) return; const timer = setTimeout(() => setToast(''), 6500); return () => clearTimeout(timer);}, [toast]);
  useEffect(() => window.research.on((event, data) => {
    if (event === 'data.changed' || event === 'job.changed') {refresh(); setStatus('所有更改保存在本机');}
    if (event === 'job.progress') setStatus(data.message);
    if (event === 'connection.status') {notify(data.message); refresh();}
    if (event === 'backend.error') {setError(data.message); setStatus('本地服务未连接');}
    if (event === 'menu.import') importFiles();
    if (event === 'menu.search') document.querySelector<HTMLInputElement>('[data-search]')?.focus();
  }), [refresh, importFiles]);
  useEffect(() => {Promise.all([api('library.stats'), api('collections.list')]).then(([s, c]) => {setStats(s); setCollections(c);}).catch(fail);}, [tick, fail]);
  useEffect(() => {if (view === 'duplicates') Promise.all([api('items.duplicates'), api('items.latestMerge')]).then(([groups, latest]) => {setDuplicates(groups); setUndo(latest?.id || null);}).catch(fail);}, [view, tick, fail]);
  useEffect(() => {
    const id = ++requestId.current; setLoading(true); setError('');
    api('items.list', {q: query, view, collectionId: collection, sort, direction: sort === 'title' ? 'asc' : 'desc', offset: (page - 1) * 200, limit: 200, ...filters})
      .then(data => {if (id === requestId.current) {setResult(data); setSelected(old => old.filter(x => data.items.some((i: Data) => i.id === x)));}})
      .catch(e => {if (id === requestId.current) setError(useErrorText(e));}).finally(() => {if (id === requestId.current) setLoading(false);});
  }, [query, view, collection, sort, page, filters, tick]);
  useEffect(() => {
    let cancelled = false;
    if (selected.length === 1) api('items.get', {id: selected[0]}).then(data => {if (!cancelled) setItem(data);}).catch(fail);
    else setItem(null);
    return () => {cancelled = true;};
  }, [selected, tick, fail]);
  const rows = useVirtualizer({count: result.items.length, getScrollElement: () => scroll.current, estimateSize: () => 68, overscan: 8});
  function nav(nextModule: string, nextView = 'all', nextCollection: string | null = null) {setModule(nextModule); setView(nextView); setCollection(nextCollection); setPage(1); setFilters({}); setQ(''); setSelected([]); setActiveTab('library'); if (nextView === 'recent') setSort('created');}
  function openRelations(itemIds: string[]) {setRelationSeed(Array.from(new Set(itemIds))); nav('relations');}
  function openResearchAsk(itemId: string, question: string) {setAskSeed({itemId,question}); nav('researchAsk');}
  function openReader(attachmentId: string, title = 'PDF 文献', pageNumber?: number, annotationId?: string) {
    setTabs(old => old.some(t => t.id === attachmentId) ? old.map(t => t.id === attachmentId ? {...t, page: pageNumber, annotationId, stamp: Date.now()} : t) : [...old, {id: attachmentId, title, page: pageNumber, annotationId, stamp: Date.now()}]);
    setActiveTab(attachmentId);
  }
  function selectItem(id: string, multi = false, range = false) {
    if (range && selected.length) {
      const a = result.items.findIndex((x: Data) => x.id === selected.at(-1)), b = result.items.findIndex((x: Data) => x.id === id);
      setSelected(result.items.slice(Math.min(a, b), Math.max(a, b) + 1).map((x: Data) => x.id));
    } else setSelected(old => multi ? old.includes(id) ? old.filter(x => x !== id) : [...old, id] : [id]);
  }
  const bulk = (action: string, value?: any) => run(() => api('items.bulk', {ids: selected, action, value}), '已更新所选文献');
  const confirmPermanentDelete = (ids?: string[]) => setModal({type: 'confirm', title: ids ? '永久删除所选文献' : '清空回收站',
    text: '将永久删除题录、笔记、批注、阅读记录和库内托管附件。外部链接文件不会删除；此操作无法撤销。',
    action: async () => {const result = await api('items.deletePermanently', ids ? {ids} : {}); setSelected([]); return result;}});
  const title = collection ? collections.find(c => c.id === collection)?.name || '集合' : ({all: '我的文献', recent: '最近添加', unread: '未读文献', starred: '星标文献', trash: '回收站', duplicates: '重复条目'} as Data)[view];
  function tree(parent: string | null, depth = 0): ReactNode {return collections.filter(c => c.parentId === parent).map(c => <div key={c.id}><div className={'tree-row ' + (collection === c.id ? 'active' : '')} style={{paddingLeft: 13 + depth * 17}}><button onClick={() => nav('library', 'all', c.id)}><Folder size={18}/><span>{c.name}</span><small>{c.count}</small></button><button className="icon tree-more" aria-label={'管理集合 ' + c.name} onClick={() => setModal({type: 'collection', value: c})}><DotsThree/></button></div>{tree(c.id, depth + 1)}</div>);}
    const activeReader = tabs.find(t => t.id === activeTab);
  return <div className={"desktop-shell " + (collapsed ? "inspector-collapsed " : "") + (activeReader && readingSidebarCollapsed ? "reading-sidebar-collapsed" : "")} style={{"--inspector": collapsed ? "0px" : undefined} as any} onDragOver={e => {if (e.dataTransfer.types.includes('Files')) e.preventDefault();}} onDrop={async e => {if (e.dataTransfer.files.length) {e.preventDefault(); try {setModal({type: 'import', preview: await window.research.dropped(e.dataTransfer.files)});} catch(e) {fail(e);}}}}>
    <header className="titlebar"><div className="brandmark"><img src={brandLogo} alt="文献工作台"/></div><span>文献工作台</span><small>个人科研空间</small><div className="window-actions"><button aria-label="最小化" onClick={() => window.research.window('minimize')}><Minus/></button><button aria-label="最大化" onClick={() => window.research.window('maximize')}><Square size={13}/></button><button aria-label="关闭" onClick={() => window.research.window('close')}><X/></button></div></header>
    <div className="app-body"><aside className="sidebar"><div className="sidebar-heading">文献库<span className="local-pill">本地</span></div><nav>
      <button className={'nav-item ' + (module === 'library' && view === 'all' && !collection ? 'active' : '')} onClick={() => nav('library')}><Books/>我的文献<span>{stats.items?.toLocaleString()}</span></button>
      <button className={'nav-item ' + (module === 'aiSearch' ? 'active' : '')} onClick={() => nav('aiSearch')}><Sparkle/>AI 文献检索</button>
      <button className={'nav-item ' + (module === 'researchAsk' ? 'active' : '')} onClick={() => nav('researchAsk')}><Sparkle/>多文献问答</button>
      <button className={'nav-item ' + (module === 'researchWorkspace' ? 'active' : '')} onClick={() => nav('researchWorkspace')}><Folder/>研究整理</button>
      <button className={'nav-item ' + (module === 'comparison' ? 'active' : '')} onClick={() => nav('comparison')}><Copy/>检索对比</button>
      <button className={'nav-item ' + (module === 'notes' ? 'active' : '')} onClick={() => nav('notes')}><Notebook/>阅读与笔记</button>
      <button className={'nav-item ' + (module === 'relations' ? 'active' : '')} onClick={() => nav('relations')}><Sparkle/>研究关联</button>
      <button className={'nav-item ' + (module === 'writing' ? 'active' : '')} onClick={() => nav('writing')}><BookOpen/>写作引用</button>
      <button className={'nav-item ' + (module === 'journals' ? 'active' : '')} onClick={() => nav('journals')}><Compass/>期刊选投<ArrowSquareOut size={14} className="muted"/></button>
    </nav><div className="section-label">我的集合<button className="icon" aria-label="新建集合" onClick={() => setModal({type: 'collection', value: {}})}><Plus size={16}/></button></div><div className="collection-tree">{tree(null)}{!collections.length && <button className="empty-collection" onClick={() => setModal({type: 'collection', value: {}})}><Plus size={15}/>创建第一个集合</button>}</div>
    <div className="section-label">常用</div><nav>{[['recent', '最近添加', Clock, null], ['unread', '未读文献', Circle, stats.unread], ['starred', '星标文献', Star, stats.starred], ['duplicates', '重复条目', Copy, null], ['trash', '回收站', Trash, stats.trash]].map(([key, label, Icon, count]: any) => <button key={key} className={'nav-item ' + (module === 'library' && view === key ? 'active' : '')} onClick={() => nav('library', key)}><Icon/>{label}{!!count && <span>{count}</span>}</button>)}</nav>
    {stats.tags.length > 0 && <><div className="section-label">标签</div><div className="sidebar-tags">{stats.tags.map((tag: Data) => <button className={filters.tag === tag.name ? 'active' : ''} key={tag.name} onClick={() => {nav('library'); setFilters({tag: tag.name});}}><i style={{background: tag.color}}/>{tag.name}</button>)}</div></>}
    <div className="sidebar-bottom"><button className={'nav-item ' + (module === 'data' ? 'active' : '')} onClick={() => nav('data')}><Database/>数据中心</button><button className={'nav-item ' + (module === 'settings' ? 'active' : '')} onClick={() => nav('settings')}><GearSix/>设置</button><div className="local-space"><span className="avatar">研</span><div>我的本地空间<small>数据由你掌握</small></div><CheckCircle size={17}/></div></div></aside>
    <main className="workspace"><div className="workspace-tabs"><button className={activeTab === 'library' ? 'active' : ''} onClick={() => setActiveTab('library')}><Books size={17}/>{({library: '文献库', aiSearch: 'AI 文献检索', researchAsk: '多文献问答', researchWorkspace: '研究整理', comparison: '检索对比', notes: '阅读与笔记', relations: '研究关联', writing: '写作引用', journals: '期刊选投', data: '数据中心', settings: '设置'} as Data)[module]}</button>{tabs.map(tab => <div className={'pdf-tab ' + (activeTab === tab.id ? 'active' : '')} key={tab.id}><button title={tab.title} onClick={() => setActiveTab(tab.id)}><FilePdf size={16}/>{tab.title}</button><button className="icon" aria-label="关闭阅读标签" onClick={() => {setTabs(old => old.filter(t => t.id !== tab.id)); if (activeTab === tab.id) setActiveTab('library');}}><X size={13}/></button></div>)}</div>
    {activeReader ? <div className="reader-stage"><div className="reader-compare-bar"><button className="reader-sidebar-toggle" aria-label={readingSidebarCollapsed ? "展开主导航栏" : "收起主导航栏"} aria-expanded={!readingSidebarCollapsed} title={readingSidebarCollapsed ? "展开主导航栏" : "收起主导航栏"} onClick={() => setReadingSidebarCollapsed(value => !value)}><List size={16}/>{readingSidebarCollapsed ? "展开导航" : "收起导航"}</button><span>PDF 阅读</span><select aria-label="双文献对照" value={compareId === activeReader.id ? '' : compareId} onChange={e=>setCompareId(e.target.value)}><option value="">单篇阅读</option>{tabs.filter(tab=>tab.id!==activeReader.id).map(tab=><option key={tab.id} value={tab.id}>对照：{tab.title}</option>)}</select>{compareId && compareId!==activeReader.id && <button onClick={()=>setCompareId('')}>退出对照</button>}</div><div className={compareId && compareId!==activeReader.id ? 'reader-compare-grid' : 'reader-single'}><Reader key={activeReader.id} attachmentId={activeReader.id} jumpPage={activeReader.page} jumpAnnotation={activeReader.annotationId} stamp={activeReader.stamp} notify={notify} fail={fail} onNote={() => nav('notes')} onResearchAsk={openResearchAsk}/>{compareId && compareId!==activeReader.id && <Reader key={compareId} attachmentId={compareId} notify={notify} fail={fail} onNote={() => nav('notes')} onResearchAsk={openResearchAsk}/>}</div></div> : module === 'writing' ? <Writing tick={tick} notify={notify}/> : module === 'comparison' ? <Comparison tick={tick} notify={notify}/> : module === 'library' ? <>
      <div className="library-header"><div><div className="breadcrumb">个人文献库 <span>/</span> {collection ? '我的集合' : '全部收藏'}</div><h1>{title}<span>{result.total.toLocaleString()} 篇文献</span></h1></div><div className="actions">{view === 'trash' && result.total > 0 && <button className="danger" onClick={() => confirmPermanentDelete()}>清空回收站</button>}<button className="primary" onClick={() => importFiles()}><Plus size={18}/>导入文献</button><button onClick={() => setModal({type: 'metadata'})}>通过 DOI 添加</button><button className="icon" title="手动新建条目" aria-label="手动新建条目" onClick={() => setModal({type: 'edit', item: null})}><DotsThree size={23}/></button></div></div>
      {view === 'duplicates' ? <div className="duplicates-body"><p className="muted">根据 DOI 或标题与年份查找重复项。合并保留所选主条目字段，将附件、笔记和标签归入主条目。</p>{undo && <div className="notice">最近一次合并已完成。<button onClick={() => run(() => api('items.undoMerge', {eventId: undo}), '已撤销合并').then(v => v && setUndo(null))}>撤销合并</button></div>}{duplicates.length ? duplicates.map((g: Data) => <div className="duplicate-group" key={g.key}>{g.items.map((i: Data) => <div key={i.id}><FilePdf/><span><strong>{i.title}</strong><small>{authorText(i)} · {yearText(i)} · {i.citationKey}</small></span><button onClick={() => setModal({type: 'confirm', title: '合并重复条目', text: '将以此条目为主条目。其他条目进入回收站，附件、笔记和标签会合并，可撤销最近一次合并。', action: async () => {const r = await api('items.merge', {targetId: i.id, sourceIds: g.items.filter((j: Data) => j.id !== i.id).map((j: Data) => j.id)}); setUndo(r.id);}})}>保留此项并合并</button></div>)}</div>) : <Empty icon={<Copy size={34}/>} title="没有发现重复条目">导入时也会检查 DOI、题名和附件内容。</Empty>}</div> : <>
      <div className="library-tools"><Search value={q} onChange={setQ}/><div className="filter-row"><select aria-label="搜索字段" value={filters.field || 'all'} onChange={e => {setFilters({...filters, field: e.target.value}); setPage(1);}}><option value="all">全部字段与全文</option><option value="title">标题</option><option value="authors">作者</option><option value="doi">DOI</option><option value="container">期刊</option></select><select aria-label="年份筛选" value={filters.year || ''} onChange={e => {setFilters({...filters, year: e.target.value}); setPage(1);}}><option value="">全部年份</option>{stats.years.map((y: string) => <option key={y}>{y}</option>)}</select><select aria-label="阅读状态筛选" value={filters.readingState || ''} onChange={e => {setFilters({...filters, readingState: e.target.value}); setPage(1);}}><option value="">全部状态</option>{Object.entries(stateText).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select><select aria-label="附件筛选" value={filters.hasAttachment || ''} onChange={e => {setFilters({...filters, hasAttachment: e.target.value}); setPage(1);}}><option value="">全部附件</option><option value="yes">有附件</option><option value="no">无附件</option></select><button onClick={()=>setModal({type:'advanced'})}>高级检索{filters.advanced?' · 已启用':''}</button>{filters.advanced&&<button onClick={()=>{setFilters(old=>{const next={...old};delete next.advanced;delete next.collectionIds;return next;});setPage(1);}}>清除高级条件</button>}{filters.tag && <button className="chip" onClick={() => setFilters({...filters, tag: null})}><Tag size={13}/>{filters.tag}<X size={12}/></button>}<div className="spacer"/><button className="icon" title="表格列设置" aria-label="表格列设置" onClick={() => setModal({type: "columns"})}><GearSix size={16}/></button><button className="icon" title={collapsed ? "展开信息侧栏" : "收起信息侧栏"} aria-label="切换信息侧栏" onClick={() => setCollapsed(v => !v)}><Square size={15}/></button><select aria-label="排序" value={sort} onChange={e => {setSort(e.target.value); setPage(1);}}><option value="created">添加时间 ↓</option><option value="updated">修改时间 ↓</option><option value="year">出版年份 ↓</option><option value="title">标题 A–Z</option></select></div></div>
      <div className="library-content"><section className={"table-pane " + Object.keys(columns).filter(k => !columns[k]).map(k => "hidden-" + k).join(" ")} style={{"--table-columns": gridColumns} as any}>{selected.length > 1 && <div className="selection-toolbar"><strong>已选 {selected.length} 篇</strong><button onClick={() => openRelations(selected)}><Sparkle/>关联分析</button><button onClick={() => setModal({type: 'citation', ids: selected})}>引用 / 导出</button><select aria-label="批量阅读状态" value="" onChange={e => bulk('readingState', e.target.value)}><option value="" disabled>标记状态</option>{Object.entries(stateText).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select><select aria-label="批量加入集合" value="" onChange={e => bulk('collection', e.target.value)}><option value="" disabled>加入集合</option>{collections.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><button onClick={() => {setBatchTags(''); setModal({type: 'tags'});}}>加标签</button><button className="icon" title={view === 'trash' ? '恢复文献' : '移入回收站'} onClick={() => bulk(view === 'trash' ? 'restore' : 'trash')}>{view === 'trash' ? <ArrowsClockwise/> : <Trash/>}</button>{view === 'trash' && <button className="danger" onClick={() => confirmPermanentDelete(selected)}>永久删除</button>}<button className="icon" aria-label="取消选择" onClick={() => setSelected([])}><X/></button></div>}
      <div className="table-head"><label><input aria-label="选择本页全部文献" type="checkbox" checked={result.items.length > 0 && selected.length === result.items.length} onChange={e => setSelected(e.target.checked ? result.items.map((x: Data) => x.id) : [])}/></label><span>标题</span>{[["authors","作者"],["year","年份"],["container","期刊 / 来源"],["state","状态"]].map(([k,label]) => <span className={"col-" + k} key={k}>{label}<i role="separator" aria-label={"调整"+label+"列宽"} className="column-resizer" onPointerDown={e => resizeColumn(e,k)}/></span>)}</div>
      {error ? <ErrorBox message={error} retry={refresh}/> : loading && !result.items.length ? <Busy/> : !result.items.length ? <Empty icon={<Books size={37}/>} title={query || Object.values(filters).some(Boolean) ? '没有匹配的文献' : view === 'trash' ? '回收站是空的' : '从第一篇文献开始'} action={view !== 'trash' && <button className="primary" onClick={() => importFiles()}><Plus/>导入文献</button>}>{query ? '试试其他关键词，或调整筛选条件。' : '拖入 PDF、RIS、BibTeX 或 CSL JSON，也可通过 DOI 添加。'}</Empty> : <div className="table-scroll" ref={scroll} role="grid" aria-label="文献列表"><div style={{height: rows.getTotalSize(), position: 'relative'}}>{rows.getVirtualItems().map(row => {const i = result.items[row.index]; return <div role="row" aria-selected={selected.includes(i.id)} tabIndex={0} className={'document-row ' + (selected.includes(i.id) ? 'selected' : '')} key={i.id} style={{position: 'absolute', top: 0, left: 0, width: '100%', height: 68, transform: `translateY(${row.start}px)`}} onClick={e => selectItem(i.id, e.ctrlKey || e.metaKey, e.shiftKey)} onContextMenu={e => {e.preventDefault(); if (!selected.includes(i.id)) setSelected([i.id]); setContext({x: Math.min(e.clientX, innerWidth-200), y: Math.min(e.clientY, innerHeight-275)});}} onKeyDown={e => {if (e.key === 'Enter') selectItem(i.id); if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {e.preventDefault(); const index = Math.max(0, Math.min(result.items.length-1, row.index + (e.key === 'ArrowDown' ? 1 : -1))); selectItem(result.items[index].id, false, e.shiftKey); rows.scrollToIndex(index); setTimeout(() => document.querySelectorAll<HTMLElement>('.document-row')[index - (rows.getVirtualItems()[0]?.index || 0)]?.focus(), 30);}}} onDoubleClick={() => i.pdfId ? openReader(i.pdfId, i.title) : setModal({type: 'edit', item: i})}><label onClick={e => e.stopPropagation()}><input aria-label={'选择 ' + i.title} type="checkbox" checked={selected.includes(i.id)} onChange={() => selectItem(i.id, true)}/></label><div className="document-title"><span className={'file-icon ' + (i.pdfId ? 'pdf' : '')}>{i.pdfId ? <FilePdf size={21}/> : <BookOpen size={21}/>}</span><span><strong>{i.title}</strong><small>{i.DOI ? 'DOI: ' + i.DOI : i.citationKey}{i.starred && <Star size={12} weight="fill"/>}</small></span></div><span className="ellipsis col-authors" title={authorText(i)}>{authorText(i) || '—'}</span><span className="col-year">{yearText(i) || '—'}</span><span className="ellipsis col-container">{i['container-title'] || '—'}</span><span className={'read-state col-state ' + i.readingState}><i/>{stateText[i.readingState]}</span></div>;})}</div></div>}
      <Pager page={page} total={result.total} size={200} setPage={setPage}/></section>
      <Inspector item={item} count={selected.length} tick={tick} onEdit={() => setModal({type: 'edit', item})} onMetadata={() => setModal({type: 'metadata', item})} onAttach={() => item && importFiles(item.id)} onReader={openReader} onCitation={() => item && setModal({type: 'citation', ids: [item.id]})} onJournal={id => {nav('journals'); setModal({type: 'journalLink', id});}} onRefresh={refresh} notify={notify} fail={fail}/></div></>}
    </> : module === 'aiSearch' ? <AiSearch tick={tick} notify={notify} fail={fail} onRelations={openRelations} onReader={openReader} onJournal={id=>{nav('journals');setModal({type:'journalLink',id});}} onLibraryChange={refresh} onLibrary={async (id, targetCollection) => {const paper = await api('items.get',{id}); nav('library','all',targetCollection||null); setQ(paper.title); setSelected([id]);}}/> : module === 'researchAsk' ? <ResearchAsk tick={tick} notify={notify} fail={fail} onReader={openReader} seed={askSeed} onSeedUsed={()=>setAskSeed(null)}/> : module === 'researchWorkspace' ? <ResearchWorkspace tick={tick} notify={notify} fail={fail} onReader={openReader} onAsk={openResearchAsk}/> : module === 'notes' ? <Notes tick={tick} onReader={openReader} notify={notify} fail={fail}/> : module === 'relations' ? <Relations tick={tick} initialItemIds={relationSeed} onInitialItemsUsed={() => setRelationSeed([])} notify={notify} fail={fail} onReader={openReader}/> : module === 'journals' ? <Journals tick={tick} initialId={modal?.type === 'journalLink' ? modal.id : undefined} notify={notify} fail={fail} onData={() => nav('data')}/> : module === 'data' ? <DataCenter tick={tick} notify={notify} fail={fail}/> : <Settings stats={stats} tick={tick} notify={notify} fail={fail} refresh={refresh}/>}
    </main></div><footer className="statusbar"><span><i/>{status}</span><span>{stats.items?.toLocaleString()} 篇文献 <b>·</b> {stats.attachments || 0} 个附件 <b>·</b> {stats.notes || 0} 篇笔记 <b>·</b> 本地文献库</span></footer>
    {toast && <div role="status" className="toast"><CheckCircle size={20}/><span>{toast}</span><button className="icon" aria-label="关闭提示" onClick={() => setToast('')}><X size={15}/></button></div>}
    {context && <><div className="context-shade" onClick={() => setContext(null)} onContextMenu={e => {e.preventDefault(); setContext(null);}}/><div className="context-menu" style={{left:context.x,top:context.y}}>{[['citation','引用与导出'],['read','标记为已读'],['unread','标记为未读'],['star','添加星标'],['tags','添加标签'],['remove','从当前集合移出'],['trash',view === 'trash' ? '恢复文献' : '移入回收站'], ...(view === 'trash' ? [['purge','永久删除']] : [])].filter(([k])=>k!=='remove'||collection).map(([key,label])=><button key={key} onClick={()=>{setContext(null); if(key==='citation')setModal({type:'citation',ids:selected}); else if(key==='tags'){setBatchTags('');setModal({type:'tags'});} else if(key==='trash')bulk(view==='trash'?'restore':'trash'); else if(key==='purge')confirmPermanentDelete(selected); else if(key==='star')bulk('starred',true); else if(key==='remove')bulk('removeCollection',collection); else bulk('readingState',key);}}>{label}</button>)}</div></>}
    {modal?.type === 'columns' && <Modal title="表格显示" close={close}><p className="muted">标题始终显示。拖动列表表头分隔线可调整列宽。</p><div className="column-options">{[['authors','作者'],['year','年份'],['container','期刊 / 来源'],['state','阅读状态']].map(([key,label])=><label key={key}><input type="checkbox" checked={columns[key]} onChange={e=>setColumns({...columns,[key]:e.target.checked})}/>{label}</label>)}</div><div className="dialog-actions"><button onClick={()=>setWidths({authors:100,year:52,container:105,state:72})}>重置列宽</button><button className="primary" onClick={close}>完成</button></div></Modal>}
    {modal?.type === 'advanced' && <AdvancedSearch collections={collections} initial={filters.advanced} initialIds={filters.collectionIds||[]} close={close} notify={notify} apply={(rule,ids)=>{setCollection(null);setView('all');setFilters(old=>({...old,advanced:rule,collectionIds:ids}));setPage(1);close();}}/>}
    {modal?.type === 'tags' && <Modal title={'为 '+selected.length+' 篇文献添加标签'} close={close}><input aria-label="批量标签" style={{width:'100%'}} placeholder="多个标签使用逗号分隔" value={batchTags} onChange={e=>setBatchTags(e.target.value)}/><div className="dialog-actions"><button onClick={close}>取消</button><button className="primary" disabled={!batchTags.trim()} onClick={()=>bulk('addTags',batchTags.split(/[,，]/).map(s=>s.trim()).filter(Boolean)).then(r=>r&&close())}>添加标签</button></div></Modal>}
    {modal?.type === 'edit' && <ItemEditor item={modal.item} collectionId={collection} close={close} done={() => {close(); refresh(); notify('题录已保存');}} fail={fail}/>}
    {modal?.type === 'import' && <ImportPreview preview={modal.preview} collections={collections} collectionId={collection} close={close} done={() => {close(); refresh(); notify('导入任务已开始，可在数据中心查看进度');}} fail={fail}/>}
    {modal?.type === 'metadata' && <MetadataDialog item={modal.item} collectionId={collection} close={close} done={() => {close(); refresh(); notify('元数据已保存');}} fail={fail}/>}
    {modal?.type === 'citation' && <CitationDialog ids={modal.ids} close={close} notify={notify} fail={fail}/>}
    {modal?.type === 'collection' && <CollectionDialog value={modal.value} collections={collections} close={close} done={() => {close(); refresh();}} fail={fail}/>}
    {modal?.type === 'confirm' && <Modal title={modal.title} close={close}><p>{modal.text}</p><div className="dialog-actions"><button onClick={close}>取消</button><button className="primary" onClick={() => run(modal.action).then(v => {if (v !== null) close();})}>确认</button></div></Modal>}
  </div>;
}
