import {useEffect, useState} from 'react';
import {FilePdf, Paperclip, PencilSimple, Plus, Star, ArrowSquareOut, BookOpen, Copy, CaretRight} from '@phosphor-icons/react';
import {api, files, type Data, authorText, yearText, stateText, sizeText} from './api';
import {Empty, Fields, Modal} from './ui';
import {NoteEditor} from './Notes';
import './fulltext.css';

type Props = {item: Data | null; count: number; tick: number; onEdit: () => void; onMetadata: () => void; onAttach: () => void; onReader: (id: string, title?: string, page?: number, annotationId?: string) => void; onCitation: () => void; onJournal: (id: number) => void; onRefresh: () => void; notify: (message: string) => void; fail: (e: any) => void};
export function Inspector(p: Props) {
  const {item, fail} = p;
  const [download, setDownload] = useState(false), [downloadUrl, setDownloadUrl] = useState('');
  const [fulltextSources, setFulltextSources] = useState<Data[]>([]);
  const [tab, setTab] = useState('info'), [notes, setNotes] = useState<Data[]>([]), [editNote, setEditNote] = useState<Data | null>(null), [journals, setJournals] = useState<Data | null>(null);
  useEffect(() => {setJournals(null); setEditNote(null); if (item) api('notes.list', {itemId: item.id}).then(setNotes).catch(fail);}, [item?.id, p.tick, fail]);
  useEffect(() => {if (item) api('fulltext.sources', {itemId: item.id}).then(setFulltextSources).catch(fail); else setFulltextSources([]);}, [item?.id, p.tick, fail]);
  async function update(patch: Data) {try {await api('items.update', {id: item!.id, revision: item!.revision, patch}); p.onRefresh();} catch(e) {fail(e);}}
  if (!item) return <aside className="inspector"><div className="inspector-tabs"><button className="active">文献信息</button></div><Empty icon={<BookOpen size={31}/>} title={p.count > 1 ? `已选择 ${p.count} 篇文献` : '让知识井然有序'}>{p.count > 1 ? '使用列表上方工具栏批量整理、引用和导出。' : '选择一篇文献，查看题录、笔记与附件。'}</Empty></aside>;
  const attachments = item.attachments || [];
  return <aside className="inspector"><div className="inspector-tabs">{[['info', '信息'], ['notes', `笔记${notes.length ? ' ' + notes.length : ''}`], ['attachments', `附件${attachments.length ? ' ' + attachments.length : ''}`]].map(([key, label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}>{label}</button>)}</div><div className="inspector-scroll"><div className="item-kind"><span><FilePdf size={16}/>{({ 'article-journal':'期刊论文','paper-conference':'会议论文',book:'图书',chapter:'书籍章节',thesis:'学位论文',report:'报告',webpage:'网页',document:'文献条目' } as Data)[item.type] || '文献条目'}</span><button className={'icon ' + (item.starred ? 'starred' : '')} aria-label="切换星标" onClick={() => update({starred: !item.starred})}><Star weight={item.starred ? 'fill' : 'regular'}/></button><button className="icon" aria-label="编辑题录" onClick={p.onEdit}><PencilSimple/></button></div><h2 className="item-title">{item.title}</h2><div className="item-authors">{authorText(item) || '作者待补充'}</div><div className="item-venue">{item['container-title']} {yearText(item)}</div>
  {tab === 'info' && <><div className="metadata-list"><div><span>文献类型</span><strong>{({ 'article-journal':'期刊论文','paper-conference':'会议论文',book:'图书',chapter:'书籍章节',thesis:'学位论文',report:'报告',webpage:'网页',document:'文献条目' } as Data)[item.type] || item.type}</strong></div><div><span>年份</span><strong>{yearText(item) || '—'}</strong></div><div><span>DOI</span>{item.DOI ? <button className="link-button" onClick={() => window.research.external('https://doi.org/' + item.DOI).catch(fail)}>{item.DOI}<ArrowSquareOut size={12}/></button> : <strong>—</strong>}</div><div><span>引用键</span><code>{item.citationKey}</code></div><div><span>阅读状态</span><select value={item.readingState} onChange={e => update({readingState: e.target.value})}>{Object.entries(stateText).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></div></div><div className="mini-actions"><button onClick={p.onMetadata}>补全元数据</button><button onClick={async () => {try {setJournals(await api('journals.link', {itemId: item.id}));} catch(e) {fail(e);}}}>查看期刊指标<CaretRight size={13}/></button></div>{journals && <div className="journal-link-results"><small>{journals.basis}</small>{journals.items.length ? journals.items.map((j: Data) => <button key={j.id} onClick={() => p.onJournal(j.id)}>{j.name}<span>IF {j.impact ?? '—'}</span></button>) : <p className="muted">本地期刊库未找到匹配项。</p>}</div>}<div className="inspector-section"><h3>摘要</h3><p className="abstract">{item.abstract || '尚未添加摘要，可编辑题录或通过 DOI 补全。'}</p></div><div className="inspector-section"><h3>附件 <span>{attachments.length}</span><button className="icon" aria-label="添加附件" onClick={p.onAttach}><Plus size={16}/></button></h3>{attachments.slice(0, 2).map((a: Data) => <div className="attachment-card" key={a.id}><FilePdf size={27}/><div><strong>{a.name}</strong><small>{sizeText(a.bytes)} · {({main:"主 PDF",supplementary:"补充材料",other:"其他附件"} as Data)[a.role] || "附件"} · {a.mode === 'managed' ? '本地副本' : '链接文件'}</small></div><button onClick={() => a.mime === 'application/pdf' ? p.onReader(a.id, item.title) : files('openAttachment', {id: a.id}).catch(fail)}>{a.mime === 'application/pdf' ? '打开 PDF' : '打开'}</button></div>)}{!attachments.length && <button className="attach-empty" onClick={p.onAttach}><Paperclip/>添加 PDF 或其他附件</button>}</div><div className="inspector-section"><h3>标签<button className="icon" aria-label="编辑标签" onClick={p.onEdit}><Plus size={16}/></button></h3><div className="tag-list">{item.tags?.length ? item.tags.map((t: string) => <span className="chip" key={t}>{t}</span>) : <small className="muted">添加标签，快速整理研究主题</small>}</div></div><details className="provenance"><summary>字段来源与记录</summary>{item.provenance?.map((s: Data, i: number) => <p key={i}>{s.source} · {s.created_at || s.createdAt}</p>)}<Fields value={{ISSN: item.ISSN, 卷: item.volume, 期: item.issue, 页码: item.page, 出版商: item.publisher}}/></details></>}
  {tab === 'attachments' && <><div className="section-heading"><h3>附件管理</h3><button onClick={() => api("fulltext.discover", {itemId: item.id}).then(result => {setFulltextSources(result.sources); p.notify(result.added ? `找到 ${result.added} 个开放全文来源` : "未发现新的开放全文来源");}).catch(fail)}>查找开放全文</button><button onClick={() => setDownload(true)}>下载 PDF</button><button onClick={p.onAttach}><Plus/>添加</button></div><div className="inspector-section"><h3>全文来源 <span>{fulltextSources.length}</span><button className="icon" aria-label="刷新全文来源" onClick={() => api('fulltext.sources', {itemId: item.id}).then(setFulltextSources).catch(fail)}><CaretRight size={14}/></button></h3>{fulltextSources.map((source: Data) => <div className="fulltext-source" key={source.id}><small>{source.origin === 'oa' ? '开放获取候选' : source.origin === 'publisher' ? '出版商 PDF 链接' : source.origin === 'record' ? '原始记录' : '手动添加'} · {({candidate:'待检查',checking:'检查中',ready:'PDF可获取',downloading:'下载中',attached:'已挂接',indexed:'已索引',landing:'论文落地页',failed:'获取失败'} as Data)[source.state] || source.state}</small><p title={source.url}>{source.url}</p>{source.error && <small>{source.error}</small>}<div className="mini-actions"><button onClick={() => window.research.external(source.resolvedUrl || source.url).catch(fail)}>打开来源</button>{source.attachmentId ? <button onClick={() => p.onReader(source.attachmentId, item.title)}>打开 PDF</button> : source.origin !== 'record' && <button onClick={() => api('fulltext.obtain', {itemId: item.id, sourceId: source.id}).then(() => p.notify('全文获取任务已创建，可在数据中心查看')).catch(fail)}>检查并获取 PDF</button>}</div></div>)}</div>{attachments.map((a: Data) => <div className="attachment-details" key={a.id}><strong><FilePdf/>{a.name}</strong><label className="attachment-role">附件类型 <select aria-label={"附件类型 " + a.name} value={a.role || "main"} onChange={e => api("attachments.setRole", {id:a.id,role:e.target.value}).then(() => {p.onRefresh();p.notify("附件类型已更新");}).catch(fail)}><option value="main">主 PDF</option><option value="supplementary">补充材料 / SI</option><option value="other">其他附件</option></select></label><p className="muted">{sizeText(a.bytes)} · {a.mode === 'managed' ? '托管副本' : '外部链接'} · {({pending: '等待索引', indexed: '可全文搜索', no_text: '扫描件，暂无文字层', protected: '需要密码', error: '解析失败'} as Data)[a.textStatus] || a.textStatus}</p><div className="mini-actions"><button onClick={() => a.mime === 'application/pdf' ? p.onReader(a.id, item.title) : files('openAttachment', {id: a.id}).catch(fail)}>打开</button><button onClick={() => files('relink', {id: a.id}).then(r => {if (r) {p.onRefresh(); p.notify('附件位置已更新；内容改变时会保留旧批注并新增附件版本');}}).catch(fail)}>重新定位</button><button onClick={() => files('revealAttachment', {id: a.id}).catch(fail)}>所在位置</button></div></div>)}</>}
  {tab === 'notes' && <><div className="section-heading"><h3>文献笔记</h3><button onClick={() => setEditNote({itemId: item.id, title: '阅读笔记', content: ''})}><Plus/>新笔记</button></div>{notes.map(n => <button className="note-card" key={n.id} onClick={() => setEditNote(n)}><strong>{n.title}</strong><p>{n.content.slice(0, 150)}</p></button>)}{!notes.length && <p className="muted">记录想法，或在 PDF 阅读器中把批注发送到笔记。</p>}</>}
  </div><div className="inspector-footer"><button onClick={p.onCitation}><Copy size={15}/>复制引用</button><button onClick={() => files('export', {ids: [item.id], format: 'bibtex'}).then(r => r && p.notify('BibTeX 已导出')).catch(fail)}>导出 BibTeX</button></div>{download && <Modal title="从公开地址获取 PDF" close={() => setDownload(false)}><p className="muted">输入公开 PDF 地址或论文落地页。若页面需要登录，请在浏览器保存全文后手动导入。</p><input aria-label="PDF 下载地址" style={{width:'100%'}} value={downloadUrl} onChange={e=>setDownloadUrl(e.target.value)} placeholder="https://…/paper.pdf"/><div className="dialog-actions"><button onClick={()=>setDownload(false)}>取消</button><button className="primary" disabled={!/^https?:\/\//.test(downloadUrl)} onClick={()=>api('fulltext.add',{itemId:item.id,url:downloadUrl}).then(async source=>{await api('fulltext.obtain',{itemId:item.id,sourceId:source.id});setDownload(false);setFulltextSources(await api('fulltext.sources',{itemId:item.id}));p.notify('全文检查与获取任务已创建，可在数据中心查看');}).catch(fail)}>开始下载</button></div></Modal>}{editNote && <NoteEditor note={editNote} close={() => setEditNote(null)} done={() => {setEditNote(null); p.onRefresh();}} onReader={p.onReader} notify={p.notify} fail={fail}/>}</aside>;
}
