import {useEffect, useState} from 'react';
import {BookOpen, Database, Globe} from '@phosphor-icons/react';
import {api, type Data, useErrorText} from './api';
import {Search, Empty, Busy, ErrorBox, Pager} from './ui';
import {Detail} from './JournalDetail';
import {countryName, numberText} from './journalPresentation';
const metric = numberText;

export function Journals({tick, initialId, notify, fail, onData}: {tick: number; initialId?: number; notify: (message: string) => void; fail: (e: any) => void; onData: () => void}) {
  const [q, setQ] = useState(''), [query, setQuery] = useState(''), [filters, setFilters] = useState<Data>({}), [sort, setSort] = useState('impact'), [page, setPage] = useState(1), [pageSize, setPageSize] = useState(8), [catalog, setCatalog] = useState<Data | null>(null), [catalogOpen, setCatalogOpen] = useState(false);
  const [result, setResult] = useState<Data>({items: [], total: 0}), [loading, setLoading] = useState(true), [error, setError] = useState(''), [id, setId] = useState<number | undefined>(initialId), [reload, setReload] = useState(0);
  useEffect(() => {if (initialId) setId(initialId);}, [initialId]);
  useEffect(() => {const t = setTimeout(() => {setQuery(q); setPage(1); if(q.trim()) setSort('relevance');}, 250); return () => clearTimeout(t);}, [q]);
  useEffect(() => {let cancelled = false; setLoading(true); setError(''); api('journals.list', {q: query, filters, sort, page, pageSize}).then(r => {if (!cancelled) setResult(r);}).catch(e => {if (!cancelled) setError(useErrorText(e));}).finally(() => {if (!cancelled) setLoading(false);}); return () => {cancelled = true;};}, [query, filters, sort, page, pageSize, tick, reload]);
  function filter(key: string, value: any) {setFilters(old => {const next = {...old}; if (value === '') delete next[key]; else next[key] = value; return next;}); setPage(1);}
  if (id) return <Detail id={id} onSelect={setId} back={() => setId(undefined)} fail={fail} notify={notify}/>;
  return <div className="module-page journals-page"><div className="page-heading"><div className="eyebrow">FIND THE RIGHT JOURNAL</div><div className="heading-row"><div><h1>期刊选投</h1><p>从本地期刊数据出发，找到适合研究的发表方向。</p></div><button onClick={onData}><Database/>数据与覆盖状态</button></div></div><div className="journal-search-panel"><Search value={q} onChange={setQ} placeholder="搜索期刊名称、ISSN 或出版商…"/><div className="journal-filter-grid">{[['fqb', '中科院分区', [['1', '1 区'], ['2', '2 区'], ['3', '3 区'], ['4', '4 区']]], ['jcr', 'JCR 分区', ['Q1', 'Q2', 'Q3', 'Q4']], ['minImpact', '影响因子', [['30', '≥ 30'], ['20', '≥ 20'], ['10', '≥ 10'], ['5', '≥ 5']]], ['ccf', 'CCF 等级', ['A', 'B', 'C']], ['publisher', '出版商', ['Elsevier', 'Springer Nature', 'IEEE', 'ACM', 'Nature Portfolio']]].map(([key, label, options]: any) => <label key={key}>{label}<select value={filters[key] || ''} onChange={e => filter(key, e.target.value)}><option value="">全部</option>{options.map((o: any) => <option key={Array.isArray(o) ? o[0] : o} value={Array.isArray(o) ? o[0] : o}>{Array.isArray(o) ? o[1] : o}</option>)}</select></label>)}</div><div className="journal-search-bottom"><button className="link-button" onClick={() => {setCatalogOpen(!catalogOpen); if (!catalog) api('journals.catalog').then(setCatalog).catch(fail);}}><Globe size={17}/>按学科与国家浏览</button><label className="check-label"><input type="checkbox" checked={filters.oa === true} onChange={e => filter('oa', e.target.checked ? true : '')}/>开放获取</label><label className="check-label"><input type="checkbox" checked={filters.warning === true} onChange={e => filter('warning', e.target.checked ? true : '')}/>预警期刊</label><div className="spacer"/>{Object.keys(filters).length > 0 && <button className="link-button" onClick={() => {setFilters({}); setPage(1);}}>清空筛选</button>}</div>{catalogOpen && catalog && <div className="catalog-panel"><label>学科目录<select value={filters.category || ''} onChange={e => {filter('category', e.target.value); setPageSize(50);}}><option value="">全部学科</option>{catalog.category.map((c: Data) => <option key={c.name} value={c.name}>{c.name}（{c.count}）</option>)}</select></label><label>国家 / 地区<select value={filters.country || ''} onChange={e => {filter('country', e.target.value); setPageSize(50);}}><option value="">全部国家 / 地区</option>{catalog.country.map((c: Data) => <option key={c.name} value={c.name}>{countryName(c.name)}（{c.count}）</option>)}</select></label><small>本地 OA {catalog.oa.toLocaleString()} · 预警 {catalog.warning.toLocaleString()} · 学科待补充 {catalog.unclassified.toLocaleString()}</small></div>}</div>
  <div className="results-heading"><span>找到 <strong>{result.total.toLocaleString()}</strong> 本期刊 <small>· 本地可查询数据</small></span><div><select aria-label="期刊排序" value={sort} onChange={e => {setSort(e.target.value); setPage(1);}}><option value="relevance">相关度</option><option value="impact">影响因子 ↓</option><option value="works">发文量 ↓</option></select><select aria-label="期刊每页条数" value={pageSize} onChange={e => {setPageSize(Number(e.target.value)); setPage(1);}}><option value={8}>8 条 / 页</option><option value={50}>50 条 / 页</option><option value={100}>100 条 / 页</option></select></div></div>
  {error ? <><ErrorBox message={error} retry={() => setReload(v => v + 1)}/><Empty icon={<Database size={36}/>} title="准备你的本地期刊库" action={<button className="primary" onClick={onData}>前往数据中心</button>}>选择已有期刊数据目录，完成一次本地索引后即可离线检索。</Empty></> : loading ? <Busy/> : result.items.length ? <div className="journal-results">{result.items.map((j: Data) => <button className="journal-card" key={j.id} onClick={() => setId(j.id)}><div className="journal-card-icon"><BookOpen size={24}/></div><div className="journal-card-main"><h2>{j.name}{j.oa && <span className="oa-tag">OA</span>}</h2><p>{j.publisher || '出版商待补充'} <span>·</span> {countryName(j.country)}</p><small>ISSN {j.issns.join(' / ') || '待补充'} <span>·</span> {j.category || '学科待补充'}</small><div className="tag-list">{j.fqb && <span className="chip">中科院 {j.fqb} 区</span>}{j.jcr && <span className="chip blue">JCR {j.jcr}</span>}{j.ccf && <span className="chip">CCF {j.ccf}</span>}{j.top && <span className="chip">TOP</span>}{j.warning && <span className="chip amber">预警 {j.warning}</span>}</div></div><div className="journal-card-numbers"><div><small>影响因子</small><strong>{metric(j.impact)}</strong></div><div><small>发文量</small><strong>{metric(j.works)}</strong></div></div></button>)}</div> : <Empty title="未找到匹配的期刊">调整筛选条件或尝试完整 ISSN。</Empty>}<Pager page={page} total={result.total} size={pageSize} setPage={setPage}/><p className="footnote">相关度采用本地名称匹配；出版集团依据已保存的出版商字段归类，可能与来源网站分类不同。未获取的指标显示为“—”。</p></div>;
}
