import {useCallback, useEffect, useState} from 'react';
import {Notebook, Plus, FloppyDisk, ClockCounterClockwise, DownloadSimple, Trash, ArrowSquareOut} from '@phosphor-icons/react';
import {api, files, type Data, dateText} from './api';
import {Modal, Search, Empty} from './ui';

function links(text: string, onReader: (id: string, title?: string, page?: number, annotationId?: string) => void) {
  return text.split(/(\[[^\]]+\]\([^)]+\))/g).map((part, i) => {
    const match = /^\[([^\]]+)\]\(([^)]+)\)$/.exec(part);
    if (!match) return part;
    const [, label, url] = match;
    if (url.startsWith('research://attachment/')) return <button className="inline-link" key={i} onClick={() => {try {const u = new URL(url); onReader(u.pathname.slice(1), '阅读摘录', Number(u.searchParams.get('page')) || 1, u.searchParams.get('annotation') || undefined);} catch {}}}>{label}<ArrowSquareOut size={12}/></button>;
    if (/^https?:\/\//.test(url)) return <button className="inline-link" key={i} onClick={() => window.research.external(url)}>{label}</button>;
    return label;
  });
}
export function Markdown({text, onReader}: {text: string; onReader: (id: string, title?: string, page?: number, annotationId?: string) => void}) {
  return <div className="markdown">{text.split('\n').map((line, index) => line.startsWith('> ') ? <blockquote key={index}>{links(line.slice(2), onReader)}</blockquote> : line.startsWith('# ') ? <h2 key={index}>{links(line.slice(2), onReader)}</h2> : line.startsWith('## ') ? <h3 key={index}>{links(line.slice(3), onReader)}</h3> : <p key={index}>{links(line, onReader)}{!line && <br/>}</p>)}</div>;
}
type EditorProps = {note: Data; close: () => void; done: () => void; onReader: (id: string, title?: string, page?: number, annotationId?: string) => void; notify: (message: string) => void; fail: (e: any) => void};
export function NoteEditor({note, close, done, onReader, notify, fail}: EditorProps) {
  const draftKey = 'note-draft:' + (note.id || note.itemId || 'standalone');
  const [draft, setDraft] = useState<Data>(() => {try {const saved = localStorage.getItem(draftKey); return saved ? {...note, ...JSON.parse(saved)} : {...note};} catch {return {...note};}});
  const [mode, setMode] = useState('edit'), [history, setHistory] = useState<Data[] | null>(null), [busy, setBusy] = useState(false), [remove, setRemove] = useState(false);
  useEffect(() => {localStorage.setItem(draftKey, JSON.stringify(draft));}, [draftKey, draft]);
  async function save() {setBusy(true); try {await api('notes.save', {...draft, tags: Array.isArray(draft.tags) ? draft.tags : JSON.parse(draft.tags || '[]')}); localStorage.removeItem(draftKey); notify('笔记已保存'); done();} catch(e) {fail(e);} finally {setBusy(false);}}
  const escape = (s: string) => s.replace(/[&<>"']/g, c => ({'&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'}[c]!));
  async function exportNote(format: string) {try {const text = format === 'html' ? '<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>' + escape(draft.title) + '</title><style>body{max-width:800px;margin:48px auto;font:16px/1.8 system-ui;white-space:pre-wrap}</style><h1>' + escape(draft.title) + '</h1><main>' + escape(draft.content) + '</main></html>' : '# ' + draft.title + '\n\n' + draft.content; const r = await files('noteExport', {format, text}); if (r) notify('笔记已导出');} catch(e) {fail(e);}}
  return <Modal title="编辑阅读笔记" close={close} wide><input className="note-title-input" aria-label="笔记标题" value={draft.title} onChange={e => setDraft({...draft, title: e.target.value})}/><div className="note-tools"><div className="tab-switch"><button className={mode === 'edit' ? 'active' : ''} onClick={() => setMode('edit')}>编辑 Markdown</button><button className={mode === 'preview' ? 'active' : ''} onClick={() => setMode('preview')}>阅读预览</button></div><span className="spacer"/>{note.id && <button onClick={() => api('notes.history', {id: note.id}).then(setHistory).catch(fail)}><ClockCounterClockwise/>历史</button>}<select aria-label="导出笔记格式" value="" onChange={e => exportNote(e.target.value)}><option value="" disabled>导出笔记</option><option value="md">Markdown</option><option value="html">HTML</option></select></div>{mode === 'edit' ? <textarea className="note-editor" aria-label="笔记内容" value={draft.content} onChange={e => setDraft({...draft, content: e.target.value})} placeholder="写下你的思考。PDF 摘录会保留返回原文的链接。"/> : <div className="note-preview"><Markdown text={draft.content} onReader={(...args) => {close(); onReader(...args);}}/></div>}{history && <div className="note-history"><h3>历史版本</h3>{history.length ? history.map(h => <div key={h.revision}><span>版本 {h.revision} · {dateText(h.created_at)}</span><button onClick={() => {setDraft({...draft, title: h.title, content: h.content}); setHistory(null); setMode('edit');}}>载入此版本内容</button></div>) : <p className="muted">首次保存后，后续修改会保留历史。</p>}</div>}<label className="note-tags">标签<input aria-label="笔记标签" placeholder="逗号分隔" value={(Array.isArray(draft.tags) ? draft.tags : JSON.parse(draft.tags || '[]')).join(', ')} onChange={e=>setDraft({...draft,tags:e.target.value.split(/[,，]/).map(v=>v.trim()).filter(Boolean)})}/></label><small className="muted">未保存的编辑会暂存为本机草稿；点击“保存笔记”写入文献库。</small><div className="dialog-actions">{note.id && <button className="danger" onClick={() => {if (!remove) setRemove(true); else api('notes.delete', {id: note.id}).then(() => {localStorage.removeItem(draftKey); done();}).catch(fail);}}><Trash size={16}/>{remove ? '确认删除笔记' : '删除'}</button>}<span className="spacer"/><button onClick={close}>稍后继续</button><button className="primary" disabled={busy} onClick={save}><FloppyDisk/>{busy ? '保存中…' : '保存笔记'}</button></div></Modal>;
}
export function Notes({tick, onReader, notify, fail}: {tick: number; onReader: (id: string, title?: string, page?: number, annotationId?: string) => void; notify: (message: string) => void; fail: (e: any) => void}) {
  const [notes, setNotes] = useState<Data[]>([]), [query, setQuery] = useState(''), [selected, setSelected] = useState<Data | null>(null), [editing, setEditing] = useState<Data | null>(null), [version, setVersion] = useState(0);
  const close = useCallback(() => setEditing(null), []);
  useEffect(() => {let cancelled = false; const timer = setTimeout(() => api('notes.list', {q: query}).then(r => {if (!cancelled) {setNotes(r); setSelected(old => r.find((n: Data) => n.id === old?.id) || r[0] || null);}}).catch(fail), 150); return () => {cancelled = true; clearTimeout(timer);};}, [query, tick, version, fail]);
  return <div className="module-page notes-page"><div className="page-heading"><div className="eyebrow">READ · THINK · CONNECT</div><div className="heading-row"><div><h1>阅读与笔记</h1><p>让摘录、思考与原文保持连接。</p></div><button className="primary" onClick={() => setEditing({title: '新建笔记', content: ''})}><Plus/>新建笔记</button></div></div><div className="notes-layout"><section className="notes-list"><Search value={query} onChange={setQuery} placeholder="搜索笔记与摘录…"/>{notes.map(n => <button key={n.id} className={'note-card ' + (selected?.id === n.id ? 'active' : '')} onClick={() => setSelected(n)}><div><Notebook size={19}/><strong>{n.title}</strong></div><p>{n.content.slice(0, 120)}</p><small>{n.itemTitle || '独立笔记'}</small><small>{dateText(n.updatedAt)}</small></button>)}</section><section className="note-reading">{selected ? <><div className="section-heading"><h2>{selected.title}</h2><button onClick={() => setEditing(selected)}>编辑笔记</button></div><p className="muted">{selected.itemTitle || '独立笔记'} · {dateText(selected.updatedAt)}</p><Markdown text={selected.content} onReader={onReader}/></> : <Empty icon={<Notebook size={38}/>} title="把阅读转化为自己的知识">在 PDF 中选取文字生成摘录，或创建一篇独立笔记。</Empty>}</section></div>{editing && <NoteEditor note={editing} close={close} done={() => {setEditing(null); setVersion(v => v + 1);}} onReader={onReader} notify={notify} fail={fail}/>}</div>;
}
