import {useEffect, useState} from 'react';
import {api, type Data, useErrorText} from './api';
import {Busy, ErrorBox} from './ui';
import './searchEvaluation.css';

export function SearchEvaluation({sessionId,runId}: {sessionId:string;runId?:string}) {
  const [report,setReport]=useState<Data|null>(null),[drafts,setDrafts]=useState<Data>({}),[busy,setBusy]=useState(''),[error,setError]=useState('');
  useEffect(()=>{let live=true;setReport(null);setError('');api('searchEvaluation.report',{sessionId,runId}).then(value=>{if(live){setReport(value);setDrafts(Object.fromEntries(value.items.map((item:Data)=>[item.id,{grade:item.evaluation?.grade??'',hardMatch:item.evaluation?.hard_match||'unknown',note:item.evaluation?.note||''}])));}}).catch(e=>live&&setError(useErrorText(e)));return()=>{live=false;};},[sessionId,runId]);
  async function save(id:string){const draft=drafts[id];if(draft?.grade==='')return;setBusy(id);setError('');try{const result=await api('searchEvaluation.save',{sessionId,runId,candidateId:id,grade:Number(draft.grade),hardMatch:draft.hardMatch,note:draft.note});setReport(result);}catch(e){setError(useErrorText(e));}finally{setBusy('');}}
  const update=(id:string,part:Data)=>setDrafts(old=>({...old,[id]:{...old[id],...part}}));
  return <section className="search-evaluation"><header><h2>检索质量人工评测</h2><p>当前版本按条件匹配优先排列的前 20 篇。只对已人工标注的候选计算相关性和硬条件比例；未标注不算作通过。</p></header>{error&&<ErrorBox message={error}/>} {!report?<Busy text="载入评测样本…"/>:<><div className="evaluation-metrics"><div><strong>{report.labelled}/{report.topK}</strong><span>已标注</span></div><div><strong>{report.relevantAmongLabelled===null?'—':Math.round(report.relevantAmongLabelled*100)+'%'}</strong><span>已标注中相关（等级 ≥2）</span></div><div><strong>{report.hardPassAmongLabelled===null?'—':Math.round(report.hardPassAmongLabelled*100)+'%'}</strong><span>已判断硬条件中通过（{report.hardLabelled} 篇）</span></div><div><strong>{report.duplicateCount}</strong><span>Top {report.topK} 重复记录</span></div><div><strong>{report.pdfAttachedCount}/{report.importedCount}</strong><span>已导入中挂接 PDF</span></div></div><p className="evaluation-sources">来源覆盖：{Object.entries(report.sourceCoverage||{}).map(([source,count])=>`${source} ${count}`).join(' · ')||'暂无'}</p><div className="evaluation-list">{report.items.map((item:Data,index:number)=><article key={item.id}><div><span>#{index+1}</span><strong>{item.title}</strong><small>{item.year||'年份未知'} · {(item.sources||[]).join('、')}{item.evaluation?.updated_at&&' · 已标注'}</small></div><label>相关性<select value={drafts[item.id]?.grade??''} onChange={e=>update(item.id,{grade:e.target.value})}><option value="">未标注</option><option value="0">0 无关</option><option value="1">1 边缘相关</option><option value="2">2 相关</option><option value="3">3 高度相关</option></select></label><label>硬条件<select value={drafts[item.id]?.hardMatch||'unknown'} onChange={e=>update(item.id,{hardMatch:e.target.value})}><option value="unknown">未判断</option><option value="pass">通过</option><option value="fail">不通过</option></select></label><label>判断依据<input value={drafts[item.id]?.note||''} onChange={e=>update(item.id,{note:e.target.value})} placeholder="可选：简述原因"/></label><button disabled={busy===item.id||drafts[item.id]?.grade===''} onClick={()=>save(item.id)}>{busy===item.id?'保存中…':'保存标注'}</button></article>)}</div></>}</section>;
}
